### ISSUE TITLE
OSS-Fuzz: build failure during coverage steps

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1260]
OSS-Fuzz is having a persistent build failure currently during the coverage steps. The error message from the report is:

```
error: /out/src/zeek/src/zeek/IP.h: No such file or directory
warning: The file '/src/zeek/src/zeek/IP.h' isn't covered.
error: /out/src/zeek/src/zeek/TunnelEncapsulation.h: No such file or directory
warning: The file '/src/zeek/src/zeek/TunnelEncapsulation.h' isn't covered.
warning: 1521 functions have mismatched data
[2020-10-30 20:58:53,561 DEBUG] Finished generating per-file code coverage summary.
[2020-10-30 20:58:53,561 DEBUG] Generating file view html index file as: "/out/report/linux/file_view_index.html".
Traceback (most recent call last):
  File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
    sys.exit(Main())
  File "/opt/code_coverage/coverage_utils.py", line 823, in Main
    return _CmdPostProcess(args)
  File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
    processor.PrepareHtmlReport()
  File "/opt/code_coverage/coverage_utils.py", line 578, in PrepareHtmlReport
    self.file_view_path)
  File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
    self.GetCoverageHtmlReportPathForFile(file_path),
  File "/opt/code_coverage/coverage_utils.py", line 423, in GetCoverageHtmlReportPathForFile
    self._MapToLocal(file_path)), '"%s" is not a file.' % file_path
AssertionError: "/src/zeek/src/zeek/TunnelEncapsulation.h" is not a file.
```

This build failure started with the addition of the IP packet analysis code, since that's when I added uses of `#include "zeek/TunnelEncapsulation.h"` and `#include "zeek/IP.h"` to the repo. Reverting those is the easy fix here, but that doesn't change that we're going to be moving to using that include format in the repo overall as part of https://github.com/zeek/zeek/issues/1079.

I can reproduce the coverage failure locally using Google's instructions. I can also fix the failure by adding `-- -ignore-filename-regex='.*/src/zeek/src/zeek/.*'` to the coverage command, but that's not a good long-term fix either. I'm also not sure if that's correct since the coverage output has 0% coverage for IP.h which doesn't seem right at all.

**Comment by jsiwek** [comment]
I expect this will be fixed by https://github.com/google/oss-fuzz/pull/4633
but a new coverage build likely won't happen until later today, so I'll just wait for that to confirm before closing this.

**Comment by jsiwek** [comment]
Latest coverage build worked.
