### ISSUE TITLE
Excessive coredump for duplicate enum definitions

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1534]
Pleas excuse the really bad an clumsy code - this was written years ago and I was trying to make use by trying to separate the code into two policies and there was overlap when I encountered the bug.  But yes, this can allow you to reproduce the coredump ( see attached a.zeek, b.zeek ) 

[reproduce.tar.gz](https://github.com/zeek/zeek/files/6395125/reproduce.tar.gz)

```
$ zeek ./a.zeek ./b.zeek
error in ././b.zeek, line 14 and ././a.zeek, line 12: conflicting definition of enum value 'Scan::LowPortTrolling' in type 'Notice::Type'
error in ././b.zeek, line 15 and ././a.zeek, line 13: conflicting definition of enum value 'Scan::LowPortScanSummary' in type 'Notice::Type'
fatal error in /home/bro/zeek-4.0.1/share/zeek/base/frameworks/notice/./main.zeek, lines 31-34: Type::AsEnumType (error/enum) (error)
Abort trap (core dumped)
```

Here is the backtrace 

```
Core was generated by `zeek -i ixl3 ../__load__.zeek'.
Program terminated with signal SIGABRT, Aborted.
#0  0x0000000802d79c2a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x0000000802d79c2a in thr_kill () from /lib/libc.so.7
#1  0x0000000802d78084 in raise () from /lib/libc.so.7
#2  0x0000000802cee279 in abort () from /lib/libc.so.7
#3  0x0000000000d31ca3 in zeek::Reporter::FatalErrorWithCore (this=0x2b32000, fmt=0x6d084c "%s") at /home/bro/install/zeek-4.0.1/src/Reporter.cc:152
#4  0x0000000000d4ae4d in zeek::Obj::BadTag (this=0x398f280, msg=0x6cbc72 "Type::AsEnumType", t1=0x70c84b "error", t2=0x707f1e "enum") at /home/bro/install/zeek-4.0.1/src/Obj.cc:98
#5  0x0000000000db463a in zeek::Type::AsEnumType (this=0x398f280) at /home/bro/install/zeek-4.0.1/src/Type.cc:159
#6  0x0000000000a95cc7 in yyparse () at parse.y:735
#7  0x0000000000bba93b in zeek::detail::setup (argc=4, argv=0x7fffffffeb38, zopts=0x0) at /home/bro/install/zeek-4.0.1/src/zeek-setup.cc:650
#8  0x0000000000a8577f in main (argc=4, argv=0x7fffffffeb38) at /home/bro/install/zeek-4.0.1/src/main.cc:13
```

```
(gdb) p *this->location
$2 = {filename = 0x395d4a0 "/home/bro/zeek-4.0.1/share/zeek/base/frameworks/notice/./main.zeek", first_line = 31, last_line = 34, first_column = 0, last_column = 0}
```

**Comment by initconf** [comment]
Please do let me know if you need any more information !
