### ISSUE TITLE
Crash zeek-4.1.0 - ZeekString.cc:80

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1694]
I do have a coredump for this one - and I don't think I've seen this one before 

anchor to find the coredump: `~/spool/tmp/post-terminate-worker-2021-07-23-11-52-00-40265-crash` 

```
Core was generated by `/home/bro/zeek-4.1.0/bin/zeek -i myri0 -U .status -p zeekctl -p zeekctl-live -p'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zeek::String::Reset (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>) at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:80
80              n = 0;
[Current thread is 1 (LWP 102281)]
(gdb) bt
#0  zeek::String::Reset (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>) at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:80
#1  zeek::String::Set (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>, str=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:151
#2  zeek::String::String (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>, str=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:51
#3  0x0000000000894988 in zeek::StringVal::StringVal (this=0x335cfb30, s=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/Val.cc:955
#4  0x0000000000c94352 in zeek::RecordVal::Assign (this=0x42b361e0, field=2, new_val=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/zeek/Val.h:1167
#5  zeek::file_analysis::detail::X509Common::ParseExtension (this=0x4d719950, ex=0x1a50dc80, h=..., global=false) at /home/bro/install/zeek-4.1.0-beta.2/src/file_analysis/analyzer/x509/X509Common.cc:281
#6  0x0000000000c95319 in zeek::file_analysis::detail::X509::EndOfFile (this=0x4d719950) at /home/bro/install/zeek-4.1.0-beta.2/src/file_analysis/analyzer/x509/X509.cc:103
#7  0x00000000009eb587 in zeek::file_analysis::File::EndOfFile (this=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/file_analysis/File.cc:557
#8  0x00000000009e502c in zeek::file_analysis::Manager::RemoveFile (this=0x23f20e0, file_id="FpOc9o3wIqZijfos2k") at /home/bro/install/zeek-4.1.0-beta.2/src/file_analysis/Manager.cc:422
#9  0x0000000000c334e2 in binpac::TLSHandshake::Handshake_Conn::proc_certificate (this=<optimized out>, is_orig=false, certificates=<optimized out>) at tls-handshake_pac.cc:240
#10 0x0000000000c3572c in binpac::TLSHandshake::Handshake_Conn::proc_v3_certificate (this=0x20e8e7b0, is_orig=false, cl=<optimized out>) at tls-handshake_pac.cc:524
#11 0x0000000000c3974e in binpac::TLSHandshake::Certificate::Parse (this=<optimized out>, t_begin_of_data=<optimized out>, t_end_of_data=<optimized out>, t_context=0x43e17a60) at tls-handshake_pac.cc:2608
#12 0x0000000000c37f06 in binpac::TLSHandshake::Handshake::Parse (this=<optimized out>, t_begin_of_data=0xeec4004 "", t_end_of_data=0xeec5308 "", t_context=0x43e17a60, t_byteorder=0) at tls-handshake_pac.cc:1212
#13 0x0000000000c37cdc in binpac::TLSHandshake::HandshakeRecord::ParseBuffer (this=0xa17cc20, t_flow_buffer=<optimized out>, t_context=0x43e17a60, t_byteorder=0) at tls-handshake_pac.cc:1002
#14 0x0000000000c3a1f3 in binpac::TLSHandshake::HandshakePDU::ParseBuffer (this=0x4e4da690, t_flow_buffer=0x21b14ba0, t_context=0x43e17a60) at tls-handshake_pac.cc:1381
#15 0x0000000000c43786 in binpac::TLSHandshake::Handshake_Flow::NewData (this=0x27c0cf00, t_begin_of_data=<optimized out>, t_end_of_data=<optimized out>) at tls-handshake_pac.cc:7351
#16 0x0000000000c289e9 in zeek::analyzer::ssl::SSL_Analyzer::SendHandshake (this=0x36fb3ea0, raw_tls_version=<optimized out>, begin=0x10 <error: Cannot access memory at address 0x10>, end=0x40 <error: Cannot access memory at address 0x40>, orig=208) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/ssl/SSL.cc:86
#17 0x0000000000c46803 in binpac::SSL::SSL_Conn::proc_handshake (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>, rec=<optimized out>, data=..., is_orig=<optimized out>) at ssl_pac.cc:484
#18 binpac::SSL::Handshake::Parse (this=0x10109f60, t_begin_of_data=0x41e5805 "\v", t_end_of_data=<optimized out>, t_context=0x5795e900) at ssl_pac.cc:1258
#19 0x0000000000c46270 in binpac::SSL::PlaintextRecord::Parse (this=0x190502a0, t_begin_of_data=<optimized out>, t_end_of_data=0x41e6b0d "I\177\340\261\236\321\f\253\334\323\252\302\037\335k\025@iw\333\036\366\260A\302\317\315\331\273^", t_context=0x5795e900, t_byteorder=0) at ssl_pac.cc:632
#20 0x0000000000c48115 in binpac::SSL::RecordText::Parse (this=<optimized out>, t_begin_of_data=0x1955fae0 "@+\001\034", t_end_of_data=<optimized out>, t_context=0x5795e900, t_byteorder=0) at ssl_pac.cc:1218
#21 0x0000000000c47dcf in binpac::SSL::SSLRecord::ParseBuffer (this=<optimized out>, t_flow_buffer=<optimized out>, t_context=0x5795e900) at ssl_pac.cc:1141
#22 0x0000000000c4878f in binpac::SSL::SSLPDU::ParseBuffer (this=0x66315c0, t_flow_buffer=0x339a0780, t_context=0x5795e900) at ssl_pac.cc:1836
#23 0x0000000000c48a06 in binpac::SSL::SSL_Flow::NewData (this=0x2b27c1e0, t_begin_of_data=<optimized out>, t_end_of_data=<optimized out>) at ssl_pac.cc:1907
#24 0x0000000000c2893f in zeek::analyzer::ssl::SSL_Analyzer::DeliverStream (this=0x36fb3ea0, len=1222, data=0x2041ea00 ".1;09\006\003U\004\003\023\062Starfield Services Root Certificate Authority - G20\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005", orig=false) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/ssl/SSL.cc:73
#25 0x0000000000a37fe1 in zeek::analyzer::Analyzer::NextStream (this=0x36fb3ea0, len=-11312, data=0x10 <error: Cannot access memory at address 0x10>, is_orig=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/Analyzer.cc:249
#26 0x0000000000a38557 in zeek::analyzer::Analyzer::ForwardStream (this=0x3a170900, len=-11312, data=0x10 <error: Cannot access memory at address 0x10>, is_orig=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/Analyzer.cc:333
#27 0x0000000000c50cd5 in zeek::analyzer::tcp::TCP_Reassembler::Deliver (this=0x4e030b40, seq=<optimized out>, len=1222, data=0x2041ea00 ".1;09\006\003U\004\003\023\062Starfield Services Root Certificate Authority - G20\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005") at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/tcp/TCP_Reassembler.cc:470
#28 zeek::analyzer::tcp::TCP_Reassembler::DeliverBlock (this=0x4e030b40, seq=<optimized out>, len=1222, data=0x2041ea00 ".1;09\006\003U\004\003\023\062Starfield Services Root Certificate Authority - G20\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005") at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/tcp/TCP_Reassembler.cc:629
#29 0x0000000000c5073c in zeek::analyzer::tcp::TCP_Reassembler::BlockInserted (this=0x4e030b40, it=...) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/tcp/TCP_Reassembler.cc:413
#30 0x0000000000c51277 in zeek::analyzer::tcp::TCP_Reassembler::DataSent (this=0x4e030b40, t=2.2219881481119652e-315, seq=140737488344016, len=<optimized out>, data=0x40 <error: Cannot access memory at address 0x40>, arg_flags=..., replaying=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/tcp/TCP_Reassembler.cc:506
#31 0x0000000000c4f28d in zeek::analyzer::tcp::TCP_Endpoint::DataSent (this=0x5757db20, t=2.2219881481119652e-315, seq=4097, len=1222, caplen=1222, data=0x829de190a <error: Cannot access memory at address 0x829de190a>, ip=<optimized out>, tp=0x829de18ea) at /home/bro/install/zeek-4.1.0-beta.2/src/analyzer/protocol/tcp/TCP_Endpoint.cc:205
#32 0x0000000000c6f69f in zeek::packet_analysis::TCP::TCPSessionAdapter::Process (this=<optimized out>, is_orig=false, tp=0x829de18ea, len=<optimized out>, ip=std::unique_ptr<zeek::IP_Hdr> = 0x56b9a9c0, data=0x829de190a <error: Cannot access memory at address 0x829de190a>, remaining=1222)
    at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc:679
#33 0x0000000000c6e05e in zeek::packet_analysis::TCP::TCPAnalyzer::DeliverPacket (this=<optimized out>, c=<optimized out>, t=<optimized out>, is_orig=<optimized out>, remaining=1222, pkt=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/protocol/tcp/TCP.cc:123
#34 0x0000000000c69385 in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket (this=0x54ad608, len=1254, data=<optimized out>, pkt=0x5602300) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc:96
#35 0x0000000000a321a8 in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x5463eb8, len=1254, data=0x829de18ea <error: Cannot access memory at address 0x829de18ea>, packet=0x5602300, identifier=6) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/Analyzer.cc:97
#36 0x0000000000c687dc in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket (this=0x5463eb8, len=<optimized out>, data=<optimized out>, packet=0x5602300) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/protocol/ip/IP.cc:260
#37 0x0000000000a321a8 in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x4f434b8, len=1274, data=0x829de18d6 <error: Cannot access memory at address 0x829de18d6>, packet=0x5602300, identifier=2048) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/Analyzer.cc:97
#38 0x0000000000a321a8 in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x550a1d8, len=1288, data=0x829de18c8 <error: Cannot access memory at address 0x829de18c8>, packet=0x5602300, identifier=1) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/Analyzer.cc:97
#39 0x0000000000a34510 in zeek::packet_analysis::Manager::ProcessPacket (this=0x23f2000, packet=0x5602300) at /home/bro/install/zeek-4.1.0-beta.2/src/packet_analysis/Manager.cc:109
#40 0x0000000000865569 in zeek::run_state::detail::dispatch_packet (pkt=0x5602300, pkt_src=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/RunState.cc:257
#41 0x00000000009d63f4 in zeek::iosource::PktSrc::Process (this=0x56022c0) at /home/bro/install/zeek-4.1.0-beta.2/src/iosource/PktSrc.cc:155
#42 0x00000000008658e0 in zeek::run_state::detail::run_loop () at /home/bro/install/zeek-4.1.0-beta.2/src/RunState.cc:315
#43 0x0000000000648d9e in main (argc=<optimized out>, argv=<optimized out>) at /home/bro/install/zeek-4.1.0-beta.2/src/main.cc:59

```

**Comment by timwoj** [comment]
This one looks like a memory corruption of some sort as well:

```
#0  zeek::String::Reset (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>) at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:80
80              n = 0;
[Current thread is 1 (LWP 102281)]
(gdb) bt
#0  zeek::String::Reset (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>) at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:80
#1  zeek::String::Set (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>, str=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:151
#2  zeek::String::String (this=0x4886b0 <vtable for zeek::detail::DFA_Machine+16>, str=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/ZeekString.cc:51
#3  0x0000000000894988 in zeek::StringVal::StringVal (this=0x335cfb30, s=0x7fffffffd3d0 "2.5.29.15") at /home/bro/install/zeek-4.1.0-beta.2/src/Val.cc:955
```

Looking at the values in gdb with a core file, that `n` value points at some random value in DFA, not anything to do with a String.

**Comment by 0xxon** [comment]
That means that we cannot do anything about this one - besides hope that other runs (with asan) actually point out the underlying cause, right?

**Comment by timwoj** [comment]
> That means that we cannot do anything about this one - besides hope that other runs (with asan) actually point out the underlying cause, right?

Pretty much.

**Comment by 0xxon** [comment]
Ok - in this case - closing, since this is a memory corruption that (hopefully) should be adressed by the other fixes. If this reoccurs - please let us know :)
