### ISSUE TITLE
Coredump - zeek-4.1.0/src/packet_analysis/protocol/ethernet/Ethernet.cc:33

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1751]
this is 4.1.0 - host sees only smtp bytes and not at a high volume ! 

Coredump anchor: `~/spool/tmp/post-terminate-worker-2021-08-25-15-35-06-60759-crash`

```
(gdb) bt
#0  zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket (this=0x4de3698, len=66, data=0xffff <error: Cannot access memory at address 0xffff>, packet=0x51a4ca0) at /usr/local/src/zeek-4.1.0/src/packet_analysis/protocol/ethernet/Ethernet.cc:33
#1  0x0000000000a31708 in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x51040f8, len=66, data=0xffff <error: Cannot access memory at address 0xffff>, packet=0x51a4ca0, identifier=1) at /usr/local/src/zeek-4.1.0/src/packet_analysis/Analyzer.cc:97
#2  0x0000000000a33a70 in zeek::packet_analysis::Manager::ProcessPacket (this=0x23f2000, packet=0x51a4ca0) at /usr/local/src/zeek-4.1.0/src/packet_analysis/Manager.cc:109
#3  0x0000000000864be9 in zeek::run_state::detail::dispatch_packet (pkt=0x51a4ca0, pkt_src=<optimized out>) at /usr/local/src/zeek-4.1.0/src/RunState.cc:257
#4  0x00000000009d59c4 in zeek::iosource::PktSrc::Process (this=0x51a4c60) at /usr/local/src/zeek-4.1.0/src/iosource/PktSrc.cc:155
#5  0x0000000000864f60 in zeek::run_state::detail::run_loop () at /usr/local/src/zeek-4.1.0/src/RunState.cc:315
#6  0x000000000064834e in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/zeek-4.1.0/src/main.cc:59

```

**Comment by timwoj** [comment]
@initconf Can you patch one of your systems with the above snippet and see if that resolves the issue?

**Comment by timwoj** [comment]
@melshershaby I hadn't realized this didn't get backported. I'll add it to the list for the next release, but I'm not entirely sure we'll have a 4.0.7 before 5.0 comes out.
