### ISSUE TITLE
Zeek worker hangs on shutdown in telemetry destruction->CAF

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#2029]
Hi,

I just set up a fresh Zeek installation on a standard Ubuntu 20.04 box. It uses a compile of the current master, with commit `d0e13a1e79c18847504fe23cd2f825f33176dc15`; `zeek -v` says `./zeek version 5.0.0-dev.231-debug`.

When running Zeek in cluster mode with one worker, running it for ~60 seconds, and then stopping it again (all with `zeekctl`), the Zeek worker will hang on shutdown. Attaching gdb results in the following traceback:

```
Thread 1 "zeek" received signal SIGINT, Interrupt.
caf::detail::shared_spinlock::lock (this=0x55635a518410) at ../auxil/broker/caf/libcaf_core/src/detail/shared_spinlock.cpp:32
32            v = flag_.load();
(gdb) bt
#0  caf::detail::shared_spinlock::lock (this=0x55635a518410) at ../auxil/broker/caf/libcaf_core/src/detail/shared_spinlock.cpp:32
#1  0x00007f19714786b5 in std::unique_lock<caf::detail::shared_spinlock>::lock (this=0x7ffdab119ab0) at /usr/include/c++/9/bits/unique_lock.h:141
#2  0x00007f1971477efd in std::unique_lock<caf::detail::shared_spinlock>::unique_lock (this=0x7ffdab119ab0, __m=...) at /usr/include/c++/9/bits/unique_lock.h:71
#3  0x00007f19714770ef in caf::actor_registry::erase (this=0x55635a5183b8, key=19) at ../auxil/broker/caf/libcaf_core/src/actor_registry.cpp:74
#4  0x00007f1971476f8c in caf::actor_registry::<lambda()>::operator()(void) const (__closure=0x55635d52e810) at ../auxil/broker/caf/libcaf_core/src/actor_registry.cpp:63
#5  0x00007f1971477a20 in caf::detail::functor_attachable<caf::actor_registry::put_impl(caf::actor_id, caf::strong_actor_ptr)::<lambda()> >::actor_exited(const caf::error &, caf::execution_unit *) (this=0x55635d52e800, fail_state=..., host=0x0) at ../auxil/broker/caf/libcaf_core/caf/detail/functor_attachable.hpp:28
#6  0x00007f19715f8c47 in caf::monitorable_actor::cleanup (this=0x55635d4b8d80, reason=..., host=0x0) at ../auxil/broker/caf/libcaf_core/src/monitorable_actor.cpp:85
#7  0x00007f19715e8018 in caf::local_actor::cleanup (this=0x55635d4b8d80, fail_state=..., host=0x0) at ../auxil/broker/caf/libcaf_core/src/local_actor.cpp:165
#8  0x00007f19714d8466 in caf::mixin::subscriber<caf::mixin::sender<caf::mixin::requester<caf::local_actor, caf::blocking_actor>, caf::blocking_actor>, caf::blocking_actor>::cleanup (this=0x55635d4b8d80, fail_state=..., ptr=0x0) at ../auxil/broker/caf/libcaf_core/caf/mixin/subscriber.hpp:47
#9  0x00007f19714d5b26 in caf::blocking_actor::cleanup (this=0x55635d4b8d80, fail_state=..., host=0x0) at ../auxil/broker/caf/libcaf_core/src/blocking_actor.cpp:393
#10 0x00007f19715e770a in caf::local_actor::on_destroy (this=0x55635d4b8d80) at ../auxil/broker/caf/libcaf_core/src/local_actor.cpp:74
#11 0x00007f19714373aa in caf::actor_storage<broker::internal::flare_actor>::data_dtor (ptr=0x55635d4b8d80) at ../auxil/broker/caf/libcaf_core/caf/actor_storage.hpp:73
#12 0x00007f197147630a in caf::intrusive_ptr_release (x=0x55635d4b8d40) at ../auxil/broker/caf/libcaf_core/src/actor_control_block.cpp:50
#13 0x00007f19712e3cb5 in caf::intrusive_ptr<caf::actor_control_block>::~intrusive_ptr (this=0x55635d522520, __in_chrg=<optimized out>) at ../auxil/broker/caf/libcaf_core/caf/intrusive_ptr.hpp:79
#14 0x00007f197147ba68 in std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >::~pair (this=0x55635d522518, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
#15 0x00007f197147ba8c in __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >, false> >::destroy<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> > > (this=0x55635a518418, __p=0x55635d522518) at /usr/include/c++/9/ext/new_allocator.h:152
#16 0x00007f197147b02f in std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >, false> > >::destroy<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> > > (__a=..., __p=0x55635d522518) at /usr/include/c++/9/bits/alloc_traits.h:496
#17 0x00007f1971479d1f in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >, false> > >::_M_deallocate_node (this=0x55635a518418, __n=0x55635d522510) at /usr/include/c++/9/bits/hashtable_policy.h:2102
#18 0x00007f19714791b2 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >, false> > >::_M_deallocate_nodes (this=0x55635a518418, __n=0x7f194c00e5e0) at /usr/include/c++/9/bits/hashtable_policy.h:2124
#19 0x00007f19714783a8 in std::_Hashtable<unsigned long, std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> >, std::allocator<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear (this=0x55635a518418) at /usr/include/c++/9/bits/hashtable.h:2063
#20 0x00007f1971478356 in std::unordered_map<unsigned long, caf::intrusive_ptr<caf::actor_control_block>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, caf::intrusive_ptr<caf::actor_control_block> > > >::clear (this=0x55635a518418) at /usr/include/c++/9/bits/unordered_map.h:844
#21 0x00007f19714777a0 in caf::actor_registry::stop (this=0x55635a5183b8) at ../auxil/broker/caf/libcaf_core/src/actor_registry.cpp:153
#22 0x00007f197147f3c7 in caf::actor_system::~actor_system (this=0x55635a518328, __in_chrg=<optimized out>) at ../auxil/broker/caf/libcaf_core/src/actor_system.cpp:398
#23 0x00007f19713081ea in broker::internal::endpoint_context::~endpoint_context (this=0x55635a518320, __in_chrg=<optimized out>) at ../auxil/broker/include/broker/internal/endpoint_access.hh:13
#24 0x00007f197130821a in __gnu_cxx::new_allocator<broker::internal::endpoint_context>::destroy<broker::internal::endpoint_context> (this=0x55635a518320, __p=0x55635a518320) at /usr/include/c++/9/ext/new_allocator.h:152
#25 0x00007f1971305e21 in std::allocator_traits<std::allocator<broker::internal::endpoint_context> >::destroy<broker::internal::endpoint_context> (__a=..., __p=0x55635a518320) at /usr/include/c++/9/bits/alloc_traits.h:496
#26 0x00007f1971304319 in std::_Sp_counted_ptr_inplace<broker::internal::endpoint_context, std::allocator<broker::internal::endpoint_context>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x55635a518310) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#27 0x0000556355c3335e in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x55635a518310) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#28 0x0000556355c2daf1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x55635ce85218, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#29 0x00007f19712e220e in std::__shared_ptr<broker::internal::endpoint_context, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x55635ce85210, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#30 0x00007f19712e222e in std::shared_ptr<broker::internal::endpoint_context>::~shared_ptr (this=0x55635ce85210, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#31 0x00007f197146831c in broker::telemetry::(anonymous namespace)::post_init_impl::~post_init_impl (this=0x55635ce851c0, __in_chrg=<optimized out>) at ../auxil/broker/src/telemetry/metric_registry.cc:212
#32 0x00007f1971468348 in broker::telemetry::(anonymous namespace)::post_init_impl::~post_init_impl (this=0x55635ce851c0, __in_chrg=<optimized out>) at ../auxil/broker/src/telemetry/metric_registry.cc:212
#33 0x00007f19714684a4 in broker::telemetry::metric_registry_impl::deref (this=0x55635ce851c0) at ../auxil/broker/include/broker/telemetry/metric_registry_impl.hh:70
#34 0x00007f1971465bbe in broker::telemetry::intrusive_ptr_release (ptr=0x55635ce851c0) at ../auxil/broker/src/telemetry/metric_registry.cc:22
#35 0x00005563561bb500 in broker::telemetry::Unref (ptr=0x55635ce851c0) at ../auxil/broker/include/broker/telemetry/fwd.hh:214
#36 0x00005563561bc239 in zeek::IntrusivePtr<broker::telemetry::metric_registry_impl>::~IntrusivePtr (this=0x5563597e9b18, __in_chrg=<optimized out>) at ../src/zeek/IntrusivePtr.h:114
#37 0x00005563561b3a9c in zeek::telemetry::Manager::~Manager (this=0x5563597e9b10, __in_chrg=<optimized out>) at ../src/telemetry/Manager.cc:30
#38 0x00005563561b3abc in zeek::telemetry::Manager::~Manager (this=0x5563597e9b10, __in_chrg=<optimized out>) at ../src/telemetry/Manager.cc:30
#39 0x0000556355c2388e in zeek::detail::terminate_zeek () at ../src/zeek-setup.cc:354
#40 0x0000556355c26e79 in zeek::run_state::detail::zeek_terminate_loop (reason=0x5563566044f8 "received termination signal") at ../src/zeek-setup.cc:992
#41 0x0000556355e28130 in zeek::run_state::detail::run_loop () at ../src/RunState.cc:354
#42 0x00005563565accde in main (argc=17, argv=0x7ffdab11a7e8) at ../src/main.cc:59
```

My node.cfg is:

```
[logger-1]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=enp1s0f0
```

Apart from this, this is an essentially unmodified standard installation.

**Comment by 0xxon** [comment]
@Neverlord - this might be one for you.

**Comment by 0xxon** [comment]
I just checked - and this does not seem to happen when using the 'topic/neverlord/alm' branch.

**Comment by Neverlord** [comment]
Thanks for double-checking with the new branch! Is the fix then simply switching to the new Broker version?

**Comment by Neverlord** [comment]
Should no longer happen since we've merged the branch in the meantime.
