### ISSUE TITLE
Segfault when redef'ing global function without &redef

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2131]
```
¡ zeek --version
zeek version 4.2.0-dev.406
```

I have not tried this with a newer version of Zeek.

```zeek
¡ cat ~/tmp/foo.zeek
export {
        global func1: function();
        global func2: function();
}

function func1()
        {
        print "func1()";
        }

function func2()
        {
        print "func2()";
        }

export {
        global func = func1;
}

event zeek_init()
        {
        func();
        }

¡ zeek ~/tmp/foo.zeek
func1()

¡ zeek ~/tmp/foo.zeek -e 'redef func = func2;'
zsh: segmentation fault  zeek ~/tmp/foo.zeek -e 'redef func = func2;'
```

This works as expected if the second export block has `global func = func1 &redef;`:

```zeek
¡ zeek ~/tmp/foo.zeek -e 'redef func = func2;'
func2()
```

I expect an error like `func does not have &redef` or something similar.

**Comment by timwoj** [comment]
ASAN Report:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==17218==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x000100984542 bp 0x7ff7bf59a3f0 sp 0x7ff7bf59a3f0 T0)
==17218==The signal is caused by a READ memory access.
==17218==Hint: address points to the zero page.
    #0 0x100984542 in zeek::Type::Tag() const Type.h:191
    #1 0x1010f5a8b in zeek::detail::add_prototype(zeek::IntrusivePtr<zeek::detail::ID> const&, zeek::Type*, std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > >*, zeek::IntrusivePtr<zeek::detail::Expr> const&) Var.cc:32
    #2 0x1010ef53a in zeek::detail::make_var(zeek::IntrusivePtr<zeek::detail::ID> const&, zeek::IntrusivePtr<zeek::Type>, zeek::detail::InitClass, zeek::IntrusivePtr<zeek::detail::Expr>, std::__1::unique_ptr<std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > >, std::__1::default_delete<std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > > > >, zeek::detail::DeclType, bool) Var.cc:229
    #3 0x1010ef05c in zeek::detail::add_global(zeek::IntrusivePtr<zeek::detail::ID> const&, zeek::IntrusivePtr<zeek::Type>, zeek::detail::InitClass, zeek::IntrusivePtr<zeek::detail::Expr>, std::__1::unique_ptr<std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > >, std::__1::default_delete<std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > > > >, zeek::detail::DeclType) Var.cc:384
    #4 0x100985f7b in build_global(zeek::detail::ID*, zeek::Type*, zeek::detail::InitClass, zeek::detail::Expr*, std::__1::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::__1::allocator<zeek::IntrusivePtr<zeek::detail::Attr> > >*, zeek::detail::DeclType) parse.y:259
    #5 0x100974305 in yyparse() parse.y:1264
    #6 0x100c1eba1 in zeek::detail::setup(int, char**, zeek::Options*) zeek-setup.cc:779
    #7 0x1022a9529 in main main.cc:13
    #8 0x11e7d451d in start+0x1cd (dyld:x86_64+0x551d)

==17218==Register values:
rax = 0x0000000000000000  rbx = 0x00007ff7bf59a660  rcx = 0x0000100000000003  rdx = 0xf2f8f8f8f2f8f2f2  
rdi = 0x0000000000000018  rsi = 0xf8f8f8f8f8f8f8f8  rbp = 0x00007ff7bf59a3f0  rsp = 0x00007ff7bf59a3f0  
 r8 = 0x00007ff7bf59abe0   r9 = 0x0000000000000002  r10 = 0x00007ff7bf59b878  r11 = 0xfffffffffffffff0  
r12 = 0x00007ff7bf59abc0  r13 = 0x0000000000000000  r14 = 0x00007ff7bf59acc0  r15 = 0x00001ffef7eb3480  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV Type.h:191 in zeek::Type::Tag() const
==17218==ABORTING
```
