### ISSUE TITLE
OSS-Fuzz build failure: filesystem.hpp not found in build directory

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2284]
```
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 577, in PrepareHtmlReport
Step #5:     self.GenerateFileViewHtmlIndexFile(per_file_coverage_summary,
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
Step #5:     self.GetCoverageHtmlReportPathForFile(file_path),
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 422, in GetCoverageHtmlReportPathForFile
Step #5:     assert os.path.isfile(
Step #5: AssertionError: "/src/zeek/build/zeek/3rdparty/ghc/filesystem.hpp" is not a file.
```

The last few oss-fuzz builds have been failing because of the above backtrace.

**Comment by awelzel** [comment]
In the oss-fuzz project there's already code to accomodate for the `zeek -> .` symlink within build.

https://github.com/google/oss-fuzz/blob/f5cc5250735debf7fadee69c426b3dcda2eb9b8f/projects/zeek/build.sh#L79-L85

I suspect something similar is needed for the new `build/3rdparty/ghc` symlink.

**Comment by awelzel** [comment]
I think the following could be a work-around on the oss-fuzz side:
```
~/projects/oss-fuzz$ git diff projects/zeek/build.sh
diff --git a/projects/zeek/build.sh b/projects/zeek/build.sh
index cfceabd3..a8f0bf1f 100644
--- a/projects/zeek/build.sh
+++ b/projects/zeek/build.sh
@@ -82,4 +82,11 @@ if [ "${SANITIZER}" = "coverage" ]; then
   # causing the coverage build to fail.
   mkdir -p $OUT/$(basename $SRC)
   cp -r $SRC/zeek $OUT/$(basename $SRC)/zeek
+
+  # Replace the 3rdpary/ghc symlink in the ./build directory with the
+  # actual contents. The symlink otherwise points into the /src directory.
+  if [ -L ${OUT}/$(basename $SRC)/zeek/build/zeek/3rdparty/ghc ]; then
+    rm ${OUT}/$(basename $SRC)/zeek/build/zeek/3rdparty/ghc
+    cp -r $SRC/zeek/auxil/filesystem/include/ghc ${OUT}/$(basename $SRC)/zeek/build/zeek/3rdparty/
+  fi
 fi
```

Possibly the following on the Zeek side (copying instead of symlinking into the build tree).

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -467,7 +467,7 @@ install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/auxil/filesystem/include/ghc
 # "zeek/3rdparty/ghc/filesystem.hpp" works within the build tree.
 execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory
                 "${CMAKE_CURRENT_BINARY_DIR}/3rdparty/")
-execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink
+execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_directory
                 "${CMAKE_CURRENT_SOURCE_DIR}/auxil/filesystem/include/ghc"
                 "${CMAKE_CURRENT_BINARY_DIR}/3rdparty/ghc")
```

Opinions?

**Comment by timwoj** [comment]
Great, thanks. I tested an oss-fuzz coverage build locally and this seems to have fixed it. I opened https://github.com/google/oss-fuzz/pull/8043 to get it merged into the upstream project. I'll leave this issue open until I get confirmation that it was merged and the build is passing again.

**Comment by timwoj** [comment]
This was confirmed fixed by OSS-Fuzz.
