### ISSUE TITLE
OSS-Fuzz 51458: Direct-leak · zeek::detail::HashKey::Allocate

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2554]
Fuzzer: zeek-smtp-fuzzer
Details: https://oss-fuzz.com/testcase-detail/5111221602353152
Minimized Test Case: [clusterfuzz-testcase-minimized-zeek-smtp-fuzzer-5111221602353152.zip](https://github.com/zeek/zeek/files/9976276/clusterfuzz-testcase-minimized-zeek-smtp-fuzzer-5111221602353152.zip)
Pcap: [fuzz.pcap.zip](https://github.com/zeek/zeek/files/9976277/fuzz.pcap.zip)

```
==21406==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 65544 byte(s) in 1 object(s) allocated from:
    #0 0x56c62d in operator new[](unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #1 0x7f378afdc74a in zeek::detail::HashKey::Allocate() zeek/src/Hash.cc:331:32
    #2 0x7f378aca0fe6 in zeek::detail::CompositeHash::EnsureTypeReserve(zeek::detail::HashKey&, zeek::Val const*, zeek::Type*, bool) const zeek/src/CompHash.cc:744:5
    #3 0x7f378aca0fe6 in zeek::detail::CompositeHash::SingleValHash(zeek::detail::HashKey&, zeek::Val const*, zeek::Type*, bool, bool, bool) const zeek/src/CompHash.cc:717:11
    #4 0x7f378aca04ad in zeek::detail::CompositeHash::MakeHashKey(zeek::Val const&, bool) const zeek/src/CompHash.cc:90:8
    #5 0x7f378b1bbf52 in zeek::TableVal::MakeHashKey(zeek::Val const&) const zeek/src/Val.cc:2676:21
    #6 0x7f378b1bbf52 in zeek::TableVal::Assign(zeek::IntrusivePtr<zeek::Val>, zeek::IntrusivePtr<zeek::Val>, bool, bool*) zeek/src/Val.cc:1539:11
    #7 0x7f378af8702a in zeek::BifFunc::find_all_bif(zeek::detail::Frame*, std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > > const*) zeek/build/strings.bif:934:7
    #8 0x7f378afab481 in zeek::detail::BuiltinFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:706:26
    #9 0x7f378ae79c2a in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:4709:16
    #10 0x7f378ae3fbb8 in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:2822:21
    #11 0x7f378b10491d in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:433:14
    #12 0x7f378b11be81 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1655:23
    #13 0x7f378b11be81 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1655:23
    #14 0x7f378afa36c4 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:406:25
    #15 0x7f378ae79c2a in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:4709:16
    #16 0x7f378ae3fbb8 in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:2822:21
    #17 0x7f378b10491d in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:433:14
    #18 0x7f378b11be81 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1655:23
    #19 0x7f378b105f13 in zeek::detail::IfStmt::DoExec(zeek::detail::Frame*, zeek::Val*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:513:25
    #20 0x7f378b104993 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:436:10
    #21 0x7f378b105f13 in zeek::detail::IfStmt::DoExec(zeek::detail::Frame*, zeek::Val*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:513:25
    #22 0x7f378b104993 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:436:10
    #23 0x7f378b11be81 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1655:23
    #24 0x7f378b11be81 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1655:23
    #25 0x7f378afa36c4 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:406:25
    #26 0x7f378ad6c269 in zeek::EventHandler::Call(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) zeek/src/EventHandler.cc:103:10
    #27 0x7f378ad67fcf in zeek::Event::Dispatch(bool) zeek/src/Event.cc:56:12
    #28 0x7f378ad696ed in zeek::EventMgr::Drain() zeek/src/Event.cc:157:13
    #29 0x5727f3 in LLVMFuzzerTestOneInput zeek/src/fuzzers/generic-analyzer-fuzzer.cc:75:19
    #30 0x440543 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #31 0x42bca2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
```

**Comment by timwoj** [comment]
Fixed via d19478f49fd04013fcdf0893872ef3d0cce41fd8 and 557ffe7bbc5c0318758ab82169b006e58639b5b3
