### ISSUE TITLE
OSS-Fuzz 51865: zeek-http-fuzzer: ASSERT: ! finished

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2560]
Fuzzer: zeek-http-fuzzer
Detailes: https://oss-fuzz.com/testcase-detail/5413166561755136
Minimized test case: [clusterfuzz-testcase-minimized-zeek-http-fuzzer-5413166561755136.zip](https://github.com/zeek/zeek/files/9976343/clusterfuzz-testcase-minimized-zeek-http-fuzzer-5413166561755136.zip)
Pcap: [fuzz.pcap.zip](https://github.com/zeek/zeek/files/9976345/fuzz.pcap.zip)

```
zeek-http-fuzzer: /src/zeek/src/analyzer/Analyzer.cc:184: virtual void zeek::analyzer::Analyzer::Done(): Assertion `! finished' failed.
==742== ERROR: libFuzzer: deadly signal
    #0 0x53b7b1 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x45a2c8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43efa3 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
    #3 0x7f08c36c23bf in libpthread.so.0
    #4 0x7f08c34db18a in __libc_signal_restore_set /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #5 0x7f08c34db18a in raise /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:48:3
    #6 0x7f08c34ba858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #7 0x7f08c34ba728 in __assert_fail_base /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:92:3
    #8 0x7f08c34cbf35 in __assert_fail /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:101:3
    #9 0x7f08c8267256 in zeek::analyzer::Analyzer::Done() zeek/src/analyzer/Analyzer.cc:184:2
    #10 0x7f08c8877da8 in zeek::analyzer::socks::SOCKS_Analyzer::Done() zeek/src/analyzer/protocol/socks/SOCKS.cc:33:42
    #11 0x7f08c82694a6 in zeek::analyzer::Analyzer::DeleteChild(std::__1::__list_iterator<zeek::analyzer::Analyzer*, void*>) zeek/src/analyzer/Analyzer.cc:552:10
    #12 0x7f08c826b001 in zeek::analyzer::Analyzer::ForwardEndOfData(bool) zeek/src/analyzer/Analyzer.cc:379:8
    #13 0x7f08c84362b5 in zeek::analyzer::http::HTTP_Entity::EndOfData() zeek/src/analyzer/protocol/http/HTTP.cc:79:36
    #14 0x7f08c843e041 in zeek::analyzer::http::HTTP_Message::Done(bool, char const*) zeek/src/analyzer/protocol/http/HTTP.cc:633:13
    #15 0x7f08c844527e in zeek::analyzer::http::HTTP_Analyzer::ReplyMade(bool, char const*) zeek/src/analyzer/protocol/http/HTTP.cc:1424:18
    #16 0x7f08c8444449 in zeek::analyzer::http::HTTP_Analyzer::Done() zeek/src/analyzer/protocol/http/HTTP.cc:855:2
    #17 0x7f08c8266f85 in zeek::analyzer::Analyzer::Done() zeek/src/analyzer/Analyzer.cc:198:9
    #18 0x7f08c89aa97b in zeek::packet_analysis::TCP::TCPSessionAdapter::Done() zeek/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc:66:12
    #19 0x7f08c73cd748 in zeek::Connection::Done() zeek/src/Conn.cc:148:13
    #20 0x7f08c802bf70 in zeek::session::Manager::Drain() zeek/src/session/Manager.cc:197:8
    #21 0x572a04 in zeek::detail::fuzzer_cleanup_one_input() zeek/src/zeek/fuzzers/fuzzer-setup.h:64:21
    #22 0x572a04 in LLVMFuzzerTestOneInput zeek/src/fuzzers/generic-analyzer-fuzzer.cc:78:2
    #23 0x440543 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #24 0x42bca2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #25 0x43154c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #26 0x45aa82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #27 0x7f08c34bc0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #28 0x421e6d in _start
```

The generated pcap isn't triggering it. Running the fuzzer does, however:
```
$ ../../build/src/fuzzers/zeek-http-fuzzer ./clusterfuzz-testcase-minimized-zeek-http-fuzzer-5413166561755136
Standalone fuzzer processing 1 inputs
  ./clusterfuzz-testcase-minimized-zeek-http-fuzzer-5413166561755136:zeek-http-fuzzer: ../src/analyzer/Analyzer.cc:184: virtual void zeek::analyzer::Analyzer::Done(): Assertion `! finished' failed.
Aborted (core dumped)
```

**Comment by timwoj** [comment]
Closed via 6ef9423f3cff13e6c73f97eb6a3a27d6f64cc320
