### ISSUE TITLE
OSS-Fuzz 52055: zeek-packet-fuzzer: heap-buffer-overflow

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2561]
Fuzzer: zeek-packet-fuzzer
Detailed report: https://oss-fuzz.com/testcase-detail/6301523957383168
Minimized testcase: [clusterfuzz-testcase-minimized-zeek-packet-fuzzer-6301523957383168.zip](https://github.com/zeek/zeek/files/9976349/clusterfuzz-testcase-minimized-zeek-packet-fuzzer-6301523957383168.zip)

```
==69976==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x606000dee640 at pc 0x7f502d6d589e bp 0x7fff46e85110 sp 0x7fff46e85108
READ of size 1 at 0x606000dee640 thread T0
    #0 0x7f502d6d589d in zeek::BuildOptionsVal(unsigned char const*, int) zeek/src/IP.cc:28:22
    #1 0x7f502d6cfeb0 in zeek::IPv6_Hdr::ToVal(zeek::IntrusivePtr<zeek::VectorVal>) const zeek/src/IP.cc:246:19
    #2 0x7f502d6d8b91 in zeek::IPv6_Hdr::ToVal() const zeek/src/IP.cc:314:9
    #3 0x7f502d6d8b91 in zeek::IPv6_Hdr_Chain::ToVal() const zeek/src/IP.cc:710:22
    #4 0x7f502d6d70d1 in zeek::IP_Hdr::ToIPHdrVal() const zeek/src/IP.cc:356:44
    #5 0x7f502d6db643 in zeek::IP_Hdr::ToPktHdrVal(zeek::IntrusivePtr<zeek::RecordVal>, int) const zeek/src/IP.cc:377:31
    #6 0x7f502e070a53 in zeek::Packet::ToRawPktHdrVal() const zeek/src/iosource/Packet.cc:148:18
    #7 0x7f502e224821 in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) zeek/src/packet_analysis/Manager.cc:152:41
    #8 0x572399 in LLVMFuzzerTestOneInput zeek/src/fuzzers/packet-fuzzer.cc:35:22
    #9 0x440483 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #10 0x42bbe2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #11 0x43148c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #12 0x45a9c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #13 0x7f50294790b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #14 0x421dad in _start

0x606000dee640 is located 0 bytes to the right of 64-byte region [0x606000dee600,0x606000dee640)
allocated by thread T0 here:
    #0 0x56c56d in operator new[](unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #1 0x7f502eade009 in std::__1::__unique_if<unsigned char []>::__unique_array_unknown_bound std::__1::make_unique<unsigned char []>(unsigned long) /usr/local/include/c++/v1/__memory/unique_ptr.h:733:28
    #2 0x7f502eade009 in zeek::detail::FuzzBuffer::Next() zeek/src/fuzzers/FuzzBuffer.cc:82:15
    #3 0x5721f3 in LLVMFuzzerTestOneInput zeek/src/fuzzers/packet-fuzzer.cc:23:19
    #4 0x440483 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #5 0x42bbe2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #6 0x43148c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #7 0x45a9c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7f50294790b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
```

This looks like a continuation of the `raw_packet` woes.

**Comment by timwoj** [comment]
Closed via 70c74e9d7161d45539fc9101d789f1d997042f2e
