### ISSUE TITLE
OSS-Fuzz 53326: Timeout in zeek-http-fuzzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2608]
Fuzzer: zeek-http-fuzzer
Detailed report: https://oss-fuzz.com/testcase-detail/4603988662419456
Minimized testcase: [clusterfuzz-testcase-minimized-zeek-http-fuzzer-4603988662419456.zip](https://github.com/zeek/zeek/files/10077067/clusterfuzz-testcase-minimized-zeek-http-fuzzer-4603988662419456.zip)
Pcap file: [53226.pcap.zip](https://github.com/zeek/zeek/files/10077068/53226.pcap.zip)

```
==744== ERROR: libFuzzer: timeout after 61 seconds
    #0 0x53b751 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x45a268 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43eeb9 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x7f396a5853bf in libpthread.so.0
    #4 0x4b2aea in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:560:37
    #5 0x4b33d9 in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:1013:16
    #6 0x56c632 in operator new[](unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #7 0x7f396e8bd7a4 in zeek::String::Set(unsigned char const*, int, bool) zeek/src/ZeekString.cc:137:6
    #8 0x7f396e8bd7a4 in zeek::String::String(unsigned char const*, int, bool) zeek/src/ZeekString.cc:44:2
    #9 0x7f396e81e94a in zeek::StringVal::StringVal(int, char const*) zeek/src/Val.cc:922:18
    #10 0x7f396e81e94a in zeek::StringVal::StringVal(std::__1::basic_string_view<char, std::__1::char_traits<char> >) zeek/src/Val.cc:926:44
    #11 0x7f396e1cfe87 in zeek::RecordVal::Assign(int, char const*) zeek/src/zeek/Val.h:1167:66
    #12 0x7f396e8bc13f in zeek::MakeCallArgumentVector(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > > const&, zeek::IntrusivePtr<zeek::RecordType> const&) zeek/src/ZeekArgs.cc:41:8
    #13 0x7f396e3bb7f8 in zeek::EventHandler::NewEvent(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*) zeek/src/EventHandler.cc:115:15
    #14 0x7f396e3b9bd2 in zeek::EventHandler::Call(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) zeek/src/EventHandler.cc:56:3
    #15 0x7f396e3b6bbf in zeek::Event::Dispatch(bool) zeek/src/Event.cc:56:12
    #16 0x7f396e3b82dd in zeek::EventMgr::Drain() zeek/src/Event.cc:157:13
    #17 0x7f396f066d0e in zeek::file_analysis::Manager::GetFileID(zeek::Tag const&, zeek::Connection*, bool) zeek/src/file_analysis/Manager.cc:434:12
    #18 0x7f396f068793 in zeek::file_analysis::Manager::EndOfFile(zeek::Tag const&, zeek::Connection*, bool) zeek/src/file_analysis/Manager.cc:188:13
    #19 0x7f396f3b2d09 in zeek::analyzer::http::HTTP_Message::Done(bool, char const*) zeek/src/analyzer/protocol/http/HTTP.cc:643:14
    #20 0x7f396f3b4998 in zeek::analyzer::http::HTTP_Message::Done() zeek/src/zeek/analyzer/protocol/http/HTTP.h:123:25
    #21 0x7f396f3b4998 in zeek::analyzer::http::HTTP_Message::EndEntity(zeek::analyzer::mime::MIME_Entity*) zeek/src/analyzer/protocol/http/HTTP.cc:705:3
    #22 0x7f396f4dc717 in zeek::analyzer::mime::MIME_Entity::EndOfData() zeek/src/analyzer/protocol/mime/MIME.cc:661:11
    #23 0x7f396f3aac65 in zeek::analyzer::http::HTTP_Entity::EndOfData() zeek/src/analyzer/protocol/http/HTTP.cc:81:31
    #24 0x7f396f3b1180 in zeek::analyzer::http::HTTP_Entity::SubmitAllHeaders() zeek/src/analyzer/protocol/http/HTTP.cc:0
    #25 0x7f396f4da562 in zeek::analyzer::mime::MIME_Entity::Deliver(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:597:4
    #26 0x7f396f3aaeb1 in zeek::analyzer::http::HTTP_Entity::Deliver(int, char const*, bool) zeek/src/analyzer/protocol/http/HTTP.cc:106:32
    #27 0x7f396f3bb7c0 in zeek::analyzer::http::HTTP_Analyzer::DeliverStream(int, unsigned char const*, bool) zeek/src/analyzer/protocol/http/HTTP.cc:0
    #28 0x7f396f1e89d4 in zeek::analyzer::SupportAnalyzer::ForwardStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:888:13
    #29 0x7f396f8cdc67 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliverOnce(int, unsigned char const*) zeek/src/analyzer/protocol/tcp/ContentLine.cc:268:6
    #30 0x7f396f8cca20 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver(int, unsigned char const*) zeek/src/analyzer/protocol/tcp/ContentLine.cc:216:11
    #31 0x7f396f8cbf57 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream(int, unsigned char const*, bool) zeek/src/analyzer/protocol/tcp/ContentLine.cc:98:2
    #32 0x7f396f1da8f4 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:249:4
    #33 0x7f396f1da924 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:243:17
    #34 0x5726e0 in LLVMFuzzerTestOneInput zeek/src/fuzzers/generic-analyzer-fuzzer.cc:68:7
    #35 0x4404e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #36 0x42bc42 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #37 0x4314ec in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #38 0x45aa22 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #39 0x7f396a37f0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #40 0x421e0d in _start
```

**Comment by timwoj** [comment]
Fixed via 3f5cb75a2a11279acd1b60bbdb35f95a47ad1089
