### ISSUE TITLE
SMB: receiving a write andx response before a request can cause an abort

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2726]
This was found by OSS-Fuzz but is considered low severity because it requires enabling the setting in Zeek that causes aborts due to scripting errors. As such, the issue is being moved into the public repo for further work.

Fuzzer: zeek-smb-fuzzer
Pcap File: [smb.pcap.zip](https://github.com/zeek/zeek/files/10513136/smb.pcap.zip)

```
==763==ERROR: AddressSanitizer: ABRT on unknown address 0x0539000002fb (pc 0x7f4211e3718b bp 0x7ffcc0fed780 sp 0x7ffcc0fed2d0 T0)
    #0 0x7f4211e3718b in raise /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
    #1 0x7f4211e16858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #2 0x7f421612120c in zeek::Reporter::ExprRuntimeError(zeek::detail::Expr const*, char const*, ...) zeek/src/Reporter.cc:172:3
    #3 0x7f4215ef2c41 in zeek::detail::Expr::RuntimeError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const zeek/src/Expr.cc:464:12
    #4 0x7f4215f39010 in zeek::detail::FieldExpr::Fold(zeek::Val*) const zeek/src/Expr.cc:3263:3
    #5 0x7f4215ef6467 in zeek::detail::UnaryExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:651:10
    #6 0x7f4215f3839f in zeek::detail::FieldExpr::Assign(zeek::detail::Frame*, zeek::IntrusivePtr<zeek::Val>) zeek/src/Expr.cc:3239:23
    #7 0x7f4215f2682d in zeek::detail::RefExpr::Assign(zeek::detail::Frame*, zeek::IntrusivePtr<zeek::Val>) zeek/src/Expr.cc:2625:6
    #8 0x7f4215f2c423 in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:2821:8
    #9 0x7f42162097ad in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:433:14
    #10 0x7f4216221021 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1697:23
    #11 0x7f4216099260 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:416:25
    #12 0x7f4215e54029 in zeek::EventHandler::Call(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) zeek/src/EventHandler.cc:106:10
    #13 0x7f4215e4fc8f in zeek::Event::Dispatch(bool) zeek/src/Event.cc:56:12
    #14 0x7f4215e513ad in zeek::EventMgr::Drain() zeek/src/Event.cc:157:13
    #15 0x5727a3 in LLVMFuzzerTestOneInput zeek/src/fuzzers/generic-analyzer-fuzzer.cc:81:19
    #16 0x4404e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #17 0x42bc42 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #18 0x4314ec in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #19 0x45aa22 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #20 0x7f4211e180b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #21 0x421e0d in _start
```

The `FieldExpr` refrerenced in frame 4 is this:
https://github.com/zeek/zeek/blob/1772a1bd6d85e14086fe4142614003c62aa22976/scripts/base/protocols/smb/smb1-main.zeek#L110

The missing field is `referenced_tree`.

From looking at the attached pcap in wireshark, it looks like we get a write andx response before we get a request. The request event handler is where `referenced_tree` would be set from, which means that the response event handler should either ignore the response or log a weird that we got them out of order. It's entirely possible for this kind of data be received via the network if we missed a packet. The SMB analyzer should resync, but it's possible the fuzzer is doing something different in that case.

**Comment by awelzel** [comment]
The pcap triggers it when ensuring DPD doesn't turn off the analyzer (which I'm unsure the fuzzer setup does).
```
$ zeek -r smb.pcap 'DPD::ignore_violations+={Analyzer::ANALYZER_SMB}'
1674515828.267935 expression error in /<...>/scripts/base/protocols/smb/./smb1-main.zeek, line 110: field value missing (SMB1::c$smb_state$current_cmd$referenced_tree)
```
I can take a look.
