### ISSUE TITLE
OSS-Fuzz 50097: Timeout in zeek-smtp-fuzzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2808]
Details: https://oss-fuzz.com/testcase-detail/5031369767518208
Minimized Test Case: [clusterfuzz-testcase-minimized-zeek-smtp-fuzzer-50097.zip](https://github.com/zeek/zeek/files/10806901/clusterfuzz-testcase-minimized-zeek-smtp-fuzzer-50097.zip)
PCAP: [50097.pcap.zip](https://github.com/zeek/zeek/files/10806919/50097.pcap.zip)

OSS Fuzz is reporting a timeout in the zeek-smtp-fuzzer:

```
ALARM: working on the last Unit for 61 seconds
--
  | and the timeout value is 60 (use -timeout=N to change)
  | ==762== ERROR: libFuzzer: timeout after 61 seconds
  | #0 0x52fff1 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
  | #1 0x471248 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
  | #2 0x456309 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
  | #3 0x7f24d41713bf in libpthread.so.0
  | #4 0x46eca5 in AddValue /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerValueBitMap.h:38:33
  | #5 0x46eca5 in HandleCmp<unsigned long> /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp:390:19
  | #6 0x46eca5 in __sanitizer_cov_trace_cmp8 /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp:483:15
  | #7 0x7f24d82ddf51 in zeek::detail::Specific_RE_Matcher::LongestMatch(unsigned char const*, int) zeek/src/RE.cc:0:8
  | #8 0x7f24d81cea67 in zeek::RE_Matcher::MatchPrefix(unsigned char const*, int) zeek/src/zeek/RE.h:234:61
  | #9 0x7f24d81cea67 in zeek::BifFunc::find_all_bif(zeek::detail::Frame*, std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > > const*) zeek/build/strings.bif:922:15
  | #10 0x7f24d81f32a5 in zeek::detail::BuiltinFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:706:26
  | #11 0x7f24d80be15f in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:4709:16
  | #12 0x7f24d8082849 in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:2822:21
  | #13 0x7f24d835341f in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:427:14
  | #14 0x7f24d836a6c1 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1640:23
  | #15 0x7f24d836a6c1 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1640:23
  | #16 0x7f24d81eb915 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:406:25
  | #17 0x7f24d80be15f in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:4709:16
  | #18 0x7f24d8082849 in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:2822:21
  | #19 0x7f24d835341f in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:427:14
  | #20 0x7f24d836a6c1 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1640:23
  | #21 0x7f24d8354a26 in zeek::detail::IfStmt::DoExec(zeek::detail::Frame*, zeek::Val*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:507:25
  | #22 0x7f24d8353495 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:430:10
  | #23 0x7f24d8354a26 in zeek::detail::IfStmt::DoExec(zeek::detail::Frame*, zeek::Val*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:507:25
  | #24 0x7f24d8353495 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:430:10
  | #25 0x7f24d836a6c1 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1640:23
  | #26 0x7f24d836a6c1 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1640:23
  | #27 0x7f24d81eb915 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:406:25
  | #28 0x7f24d7fa97c7 in zeek::EventHandler::Call(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) zeek/src/EventHandler.cc:103:10
  | #29 0x7f24d7fa56c5 in zeek::Event::Dispatch(bool) zeek/src/Event.cc:56:12
  | #30 0x7f24d7fa6dba in zeek::EventMgr::Drain() zeek/src/Event.cc:157:13
  | #31 0x5633a5 in LLVMFuzzerTestOneInput zeek/src/fuzzers/smtp-fuzzer.cc:73:19
  | #32 0x457933 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
  | #33 0x4435c2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
  | #34 0x448e0c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
  | #35 0x471a02 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #36 0x7f24d3f6b0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
  | #37 0x421ded in _start
```

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/commit/8cf1e51623beedcc5e1a393a8679a62ad71b65b9
