### ISSUE TITLE
OSS-Fuzz 57109 zeek-rdp-fuzzer: Timeout in zeek-rdp-fuzzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2942]
Fuzzer: zeek-rdp-fuzzer
Detailed report: https://oss-fuzz.com/testcase?key=6259404139003904
Reproducer test case: [clusterfuzz-testcase-minimized-zeek-rdp-fuzzer-6259404139003904.zip](https://github.com/zeek/zeek/files/11213322/clusterfuzz-testcase-minimized-zeek-rdp-fuzzer-6259404139003904.zip)
Pcap: [57109.pcap.zip](https://github.com/zeek/zeek/files/11213321/57109.pcap.zip)

```
INFO: Running with entropic power schedule (0xFF, 100).
--
  | INFO: Seed: 2791722464
  | INFO: Loaded 4 modules   (602239 inline 8-bit counters): 242 [0x7f61ae0bede8, 0x7f61ae0beeda), 222210 [0x7f61b031f2e0, 0x7f61b03556e2), 379249 [0x7f61b3a86b08, 0x7f61b3ae3479), 538 [0x5f64f0, 0x5f670a),
  | INFO: Loaded 4 PC tables (602239 PCs): 242 [0x7f61ae0beee0,0x7f61ae0bfe00), 222210 [0x7f61b03556e8,0x7f61b06b9708), 379249 [0x7f61b3ae3480,0x7f61b40acb90), 538 [0x5f6710,0x5f88b0),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_zeek_6f615cc300e6c2de585ee42e1daa3a81e4427375/revisions/zeek-rdp-fuzzer: Running 1 inputs 100 time(s) each.
  | Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/9fb2c721ac7fd4d1bcc2f8136c4ff52075a8d75fdd28452e447755ea8f9ac3b6
  | ALARM: working on the last Unit for 61 seconds
  | and the timeout value is 60 (use -timeout=N to change)
==84779== ERROR: libFuzzer: timeout after 61 seconds
    #0 0x53b761 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x45a278 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43eec9 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x7f61add9741f in libpthread.so.0
    #4 0x4578c0 in Popcountll /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerBuiltins.h:29:54
    #5 0x4578c0 in fuzzer::TracePC::AddValueForMemcmp(void*, void const*, void const*, unsigned long, bool) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp:368:46
    #6 0x4c70a6 in strcmp /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:470:3
    #7 0x7f61b1a5f781 in zeek::util::streq(char const*, char const*) [zeek/src/util.cc:1134](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/util.cc#L1134):9
    #8 0x7f61b2072e76 in zeek::RecordType::FieldOffset(char const*) const [zeek/src/Type.cc:1174](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/Type.cc#L1174):8
    #9 0x7f61b31e4431 in auto zeek::RecordVal::GetFieldAs<zeek::RecordVal>(char const*) const [zeek/src/include/zeek/Val.h:1356](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/include/zeek/Val.h#L1356):40
    #10 0x7f61b31e4431 in zeek::packet_analysis::TCP::TCPSessionAdapter::UpdateConnVal(zeek::RecordVal*) [zeek/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc:1181](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc#L1181):33
    #11 0x7f61b1b88aaa in zeek::Connection::GetVal() [zeek/src/Conn.cc:276](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/Conn.cc#L276):12
    #12 0x7f61b2aa0506 in zeek::analyzer::Analyzer::ConnVal() [zeek/src/analyzer/Analyzer.cc:821](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L821):15
    #13 0x7f61b2c78cfb in zeek::analyzer::http::HTTP_Analyzer::HTTP_Event(char const*, zeek::IntrusivePtr<zeek::StringVal>) [zeek/src/analyzer/protocol/http/HTTP.cc:1421](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/http/HTTP.cc#L1421):32
    #14 0x7f61b2c761c3 in zeek::analyzer::http::HTTP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/http/HTTP.cc:1018](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/http/HTTP.cc#L1018):7
    #15 0x7f61b2aa3944 in zeek::analyzer::SupportAnalyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:889](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L889):13
    #16 0x7f61b3184556 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliverOnce(int, unsigned char const*) [zeek/src/analyzer/protocol/tcp/ContentLine.cc:292](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/tcp/ContentLine.cc#L292):6
    #17 0x7f61b3183660 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver(int, unsigned char const*) [zeek/src/analyzer/protocol/tcp/ContentLine.cc:216](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/tcp/ContentLine.cc#L216):11
    #18 0x7f61b3182b97 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/tcp/ContentLine.cc:98](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/tcp/ContentLine.cc#L98):2
    #19 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #20 0x7f61b2a95394 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:244](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L244):17
    #21 0x7f61b2e700ed in zeek::analyzer::pia::PIA_TCP::ReplayStreamBuffer(zeek::analyzer::Analyzer*) [zeek/src/analyzer/protocol/pia/PIA.cc:444](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/pia/PIA.cc#L444):14
    #22 0x7f61b2e700ed in zeek::analyzer::pia::PIA_TCP::ActivateAnalyzer(zeek::Tag, zeek::detail::Rule const*) [zeek/src/analyzer/protocol/pia/PIA.cc:346](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/pia/PIA.cc#L346):3
    #23 0x7f61b1f98882 in zeek::detail::RuleActionEnable::DoAction(zeek::detail::Rule const*, zeek::detail::RuleEndpointState*, unsigned char const*, int) [zeek/src/RuleAction.cc:91](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/RuleAction.cc#L91):18
    #24 0x7f61b1fadc08 in zeek::detail::RuleMatcher::ExecRuleActions(zeek::detail::Rule*, zeek::detail::RuleEndpointState*, unsigned char const*, int, bool) [zeek/src/RuleMatcher.cc:1137](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/RuleMatcher.cc#L1137):11
    #25 0x7f61b1fb0dac in zeek::detail::RuleMatcher::Match(zeek::detail::RuleEndpointState*, zeek::detail::Rule::PatternType, unsigned char const*, int, bool, bool, bool) [zeek/src/RuleMatcher.cc:1032](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/RuleMatcher.cc#L1032):4
    #26 0x7f61b1fb5f46 in zeek::detail::RuleMatcherState::Match(zeek::detail::Rule::PatternType, unsigned char const*, int, bool, bool, bool, bool) [zeek/src/RuleMatcher.cc:1525](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/RuleMatcher.cc#L1525):16
    #27 0x7f61b2e6f610 in zeek::analyzer::pia::PIA::DoMatch(unsigned char const*, int, bool, bool, bool, bool, zeek::IP_Hdr const*) [zeek/src/analyzer/protocol/pia/PIA.cc:146](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/pia/PIA.cc#L146):34
    #28 0x7f61b2e6f610 in zeek::analyzer::pia::PIA_TCP::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/pia/PIA.cc:288](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/pia/PIA.cc#L288):2
    #29 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #30 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #31 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #32 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #33 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #34 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #35 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #36 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #37 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #38 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #39 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #40 0x7f61b30a2e7b in zeek::analyzer::socks::SOCKS_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/socks/SOCKS.cc:71](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/socks/SOCKS.cc#L71):3
    #41 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #42 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #43 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #44 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #45 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #46 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #47 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #48 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #49 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #50 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #51 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #52 0x7f61b30a2e7b in zeek::analyzer::socks::SOCKS_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/socks/SOCKS.cc:71](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/socks/SOCKS.cc#L71):3
    #53 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #54 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #55 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #56 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #57 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #58 0x7f61b30a2e7b in zeek::analyzer::socks::SOCKS_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/socks/SOCKS.cc:71](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/socks/SOCKS.cc#L71):3
    #59 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #60 0x7f61b2a9728c in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:333](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L333):13
    #61 0x7f61b2e8b40b in zeek::analyzer::rdp::RDP_Analyzer::DeliverStream(int, unsigned char const*, bool) [zeek/src/analyzer/protocol/rdp/RDP.cc:72](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/protocol/rdp/RDP.cc#L72):4
    #62 0x7f61b2a95364 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) [zeek/src/analyzer/Analyzer.cc:250](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/analyzer/Analyzer.cc#L250):4
    #63 0x5727ec in LLVMFuzzerTestOneInput [zeek/src/fuzzers/generic-analyzer-fuzzer.cc:74](https://github.com/zeek/zeek/blob/13648c88aa90d8302f4498c7244a5b52030e2d1c/src/fuzzers/generic-analyzer-fuzzer.cc#L74):7
    #64 0x4404f3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #65 0x42bc52 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #66 0x4314fc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #67 0x45aa32 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #68 0x7f61adb90082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
    #69 0x421e1d in _start
```

**Comment by timwoj** [comment]
Fixed via f812ce53cf3da4b34b8a0047ee807c7d9a24a288
