### ISSUE TITLE
 OSS-Fuzz 58930: zeek-pop3-fuzzer: Timeout in zeek-pop3-fuzzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3067]
Fuzzer: zeek-pop3-fuzzer
Detailed report: https://oss-fuzz.com/testcase-detail/4959095153885184
Minimized testcase: [clusterfuzz-testcase-minimized-zeek-pop3-fuzzer-4959095153885184.zip](https://github.com/zeek/zeek/files/11537669/clusterfuzz-testcase-minimized-zeek-pop3-fuzzer-4959095153885184.zip)
Pcap: [58930.pcap.zip](https://github.com/zeek/zeek/files/11537670/58930.pcap.zip)

For the pcap to reproduce it, need the following script because we don't register POP3 on port 110 by default and the dpd.sig does not actually trigger on the content.
```
global ports = { 110/tcp };

redef likely_server_ports += { ports };

event zeek_init() {
        Analyzer::register_for_ports(Analyzer::ANALYZER_POP3, ports);
}
```

Logs very many of:

```
`1684144146.686917 warning in /home/awelzel/corelight-oss/zeek-security/scripts/base/frameworks/files/./main.zeek, line 517: get_file_handle() invoked for Analyzer::ANALYZER_POP3
1684144146.686917 warning in /home/awelzel/corelight-oss/zeek-security/scripts/base/frameworks/files/./main.zeek, line 517: get_file_handle() invoked for Analyzer::ANALYZER_POP3
1684144146.686917 warning in /home/awelzel/corelight-oss/zeek-security/scripts/base/frameworks/files/./main.zeek, line 517: get_file_handle() invoked for Analyzer::ANALYZER_POP3
```

```
Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/timeout-426736d40604c9a55ee65a164056adec9aae5940
ALARM: working on the last Unit for 61 seconds
       and the timeout value is 60 (use -timeout=N to change)
==53424== ERROR: libFuzzer: timeout after 61 seconds
    #0 0x53b7c1 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x45a2d8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43ef29 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x79780b2c241f in libpthread.so.0
    #4 0x79780fdad4e2 in zeek::detail::post_execute_stmt(zeek::detail::Stmt*, zeek::detail::Frame*, zeek::Val*, zeek::detail::StmtFlowType*) zeek/src/Debug.cc:917
    #5 0x7978101db334 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1699:10
    #6 0x7978100556d0 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:418:25
    #7 0x79780ff2255a in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const zeek/src/Expr.cc:4604:16
    #8 0x7978101c3a2d in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:433:14
    #9 0x7978101db301 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) zeek/src/Stmt.cc:1697:23
    #10 0x7978100556d0 in zeek::detail::ScriptFunc::Invoke(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const zeek/src/Func.cc:418:25
    #11 0x79780fe4a43b in zeek::EventHandler::Call(std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool, double) zeek/src/EventHandler.cc:116:10
    #12 0x79780fe4620b in zeek::Event::Dispatch(bool) zeek/src/Event.cc:55:12
    #13 0x79780fe47968 in zeek::EventMgr::Drain() zeek/src/Event.cc:160:13
    #14 0x79780f60e2fa in zeek::file_analysis::File::FileEvent(zeek::EventHandlerPtr, std::__1::vector<zeek::IntrusivePtr<zeek::Val>, std::__1::allocator<zeek::IntrusivePtr<zeek::Val> > >) zeek/src/file_analysis/File.cc:623:13
    #15 0x79780f61aa33 in zeek::file_analysis::File::FileEvent(zeek::EventHandlerPtr) zeek/src/file_analysis/File.cc:612:2
    #16 0x79780f5fc792 in zeek::file_analysis::Manager::GetFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, zeek::Connection*, zeek::Tag const&, bool, bool, char const*) zeek/src/file_analysis/Manager.cc:331:9
    #17 0x79780f5fcd38 in zeek::file_analysis::Manager::DataIn(unsigned char const*, unsigned long, zeek::Tag const&, zeek::Connection*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) zeek/src/file_analysis/Manager.cc:126:15
    #18 0x79780ef8a4d0 in zeek::analyzer::mime::MIME_Mail::SubmitData(int, char const*) zeek/src/analyzer/protocol/mime/MIME.cc:1464:28
    #19 0x79780ef837af in zeek::analyzer::mime::MIME_Entity::SubmitData(int, char const*) zeek/src/analyzer/protocol/mime/MIME.cc:1207:11
    #20 0x79780ef7aeba in zeek::analyzer::mime::MIME_Entity::FlushData() zeek/src/analyzer/protocol/mime/MIME.cc:1235:3
    #21 0x79780ef7aeba in zeek::analyzer::mime::MIME_Entity::DecodeDataLine(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:1021:2
    #22 0x79780ef7aeba in zeek::analyzer::mime::MIME_Entity::NewDataLine(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:699:4
    #23 0x79780ef7998c in zeek::analyzer::mime::MIME_Entity::Deliver(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:618:4
    #24 0x79780ef7aaa3 in zeek::analyzer::mime::MIME_Entity::NewDataLine(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:694:26
    #25 0x79780ef7998c in zeek::analyzer::mime::MIME_Entity::Deliver(int, char const*, bool) zeek/src/analyzer/protocol/mime/MIME.cc:618:4
    #26 0x79780f05b593 in zeek::analyzer::mime::MIME_Message::Deliver(int, char const*, bool) zeek/src/include/zeek/analyzer/protocol/mime/MIME.h:221:14
    #27 0x79780f05b593 in zeek::analyzer::pop3::POP3_Analyzer::ProcessData(int, char const*) zeek/src/analyzer/protocol/pop3/POP3.cc:848:8
    #28 0x79780f05b593 in zeek::analyzer::pop3::POP3_Analyzer::ProcessReply(int, char const*) zeek/src/analyzer/protocol/pop3/POP3.cc:606:5
    #29 0x79780f05a02a in zeek::analyzer::pop3::POP3_Analyzer::DeliverStream(int, unsigned char const*, bool) zeek/src/analyzer/protocol/pop3/POP3.cc:83:3
    #30 0x79780ec6d274 in zeek::analyzer::SupportAnalyzer::ForwardStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:893:13
    #31 0x79780f38c1a6 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliverOnce(int, unsigned char const*) zeek/src/analyzer/protocol/tcp/ContentLine.cc:292:6
    #32 0x79780f38b2b0 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver(int, unsigned char const*) zeek/src/analyzer/protocol/tcp/ContentLine.cc:216:11
    #33 0x79780f38a7e7 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream(int, unsigned char const*, bool) zeek/src/analyzer/protocol/tcp/ContentLine.cc:98:2
    #34 0x79780ec5bf64 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:250:4
    #35 0x79780ec5bf94 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) zeek/src/analyzer/Analyzer.cc:244:17
    #36 0x5729dd in LLVMFuzzerTestOneInput zeek/src/fuzzers/generic-analyzer-fuzzer.cc:76:7
    #37 0x440553 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #38 0x42bcb2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #39 0x43155c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #40 0x45aa92 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #41 0x79780b0bb082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
    #42 0x421e7d in _start

```

**Comment by timwoj** [comment]
Fixed by 9bda48d17c313319ea833cc2aadd987bb121ea5b and https://github.com/zeek/zeek/commit/d4c99e7c3fbf2330ac6989783aa69d170a9c3530
