### ISSUE TITLE
ToRawPktHdrVal: ASAN heap-buffer-overflow reading Traces/trunc/trunc-hdr.pcap with raw_event() handler

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3069]
I was running the following script against all pcaps in testing/ to find IPv4 options using an ASAN build, was a bit surprised when a ASAN report came along

```
# options.zeek
event raw_packet(p: raw_pkt_hdr) {
        if ( ! p?$ip )
                return;

        if ( p$ip$hl != 20 )
                print p$ip;
}
```

```
$ zeek -r ../../testing/btest/Traces/trunc/trunc-hdr.pcap  ./options.zeek 
=================================================================
==572564==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000aa613b at pc 0x56245ba1e17e bp 0x7ffc9eb7d560 sp 0x7ffc9eb7d558
READ of size 1 at 0x602000aa613b thread T0                       
    #0 0x56245ba1e17d in zeek::Packet::FmtEUI48(unsigned char const*) const ../src/iosource/Packet.cc:184
    #1 0x56245ba1ea11 in zeek::Packet::ToRawPktHdrVal() const ../src/iosource/Packet.cc:120
    #2 0x56245b64b55c in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) ../src/packet_analysis/Manager.cc:147
    #3 0x56245c37dd87 in zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*) ../src/RunState.cc:290
    #4 0x56245ba243f4 in zeek::iosource::PktSrc::Process() ../src/iosource/PktSrc.cc:160
    #5 0x56245c380e6d in zeek::run_state::detail::run_loop() ../src/RunState.cc:349
    #6 0x56245cba6a46 in main ../src/main.cc:102                 
    #7 0x7f0180088d09 in __libc_start_main ../csu/libc-start.c:308
    #8 0x56245aeb5849 in _start (/home/awelzel/corelight-oss/zeek/build/src/zeek+0x9e2849)
                                                                                    
0x602000aa613b is located 10 bytes to the right of 1-byte region [0x602000aa6130,0x602000aa6131)
allocated by thread T0 here:                                                        
    #0 0x7f01889581f8 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x7f0186fac8d7  (/lib/x86_64-linux-gnu/libpcap.so.0.8+0x258d7)
    #2 0xef816  (<unknown module>)
                                          
SUMMARY: AddressSanitizer: heap-buffer-overflow ../src/iosource/Packet.cc:184 in zeek::Packet::FmtEUI48(unsigned char const*) const
```

**Comment by timwoj** [comment]
Fixed by fc78b14cd7795800bb2f96429d59f730a0aaf96e
