### ISSUE TITLE
OSS-Fuzz 60121: heap-buffer-overflow in VLANAnalyzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3294]
Fuzzer: zeek-packet-fuzzer
Detailed Report: https://oss-fuzz.com/testcase-detail/6428589923631104
Minimized test case: [clusterfuzz-testcase-minimized-zeek-packet-fuzzer-6428589923631104.fuzz.zip](https://github.com/zeek/zeek/files/12602625/clusterfuzz-testcase-minimized-zeek-packet-fuzzer-6428589923631104.fuzz.zip)
PCAP: [test.pcap.zip](https://github.com/zeek/zeek/files/12602628/test.pcap.zip)

```
==402==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6070023d7cb7 at pc 0x7aa770c4fd80 bp 0x7ffe8c8fc7e0 sp 0x7ffe8c8fc7d8
READ of size 1 at 0x6070023d7cb7 thread T0
    #0 0x7aa770c4fd7f in zeek::packet_analysis::VLAN::VLANAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/vlan/VLAN.cc:50:32
    #1 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #2 0x7aa770c4faa6 in zeek::packet_analysis::VLAN::VLANAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/vlan/VLAN.cc:0
    #3 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #4 0x7aa770c4e471 in zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/ethernet/Ethernet.cc:0
    #5 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #6 0x7aa770c41908 in zeek::packet_analysis::Manager::ProcessInnerPacket(zeek::Packet*) zeek/src/packet_analysis/Manager.cc:156:24
    #7 0x7aa770ccb3fd in zeek::packet_analysis::IPTunnel::IPTunnelAnalyzer::ProcessEncapsulatedPacket(double, zeek::Packet const*, unsigned int, unsigned int, unsigned char const*, int, std::__1::shared_ptr<zeek::EncapsulationStack>, zeek::EncapsulatingConn const&) zeek/src/packet_analysis/protocol/iptunnel/IPTunnel.cc:162:32
    #8 0x7aa770cca1db in zeek::packet_analysis::IPTunnel::IPTunnelAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/iptunnel/IPTunnel.cc:81:10
    #9 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #10 0x7aa770cc7624 in zeek::packet_analysis::GRE::GREAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/gre/GRE.cc:228:2
    #11 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #12 0x7aa770c6a51e in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) zeek/src/packet_analysis/protocol/ip/IP.cc:298:17
    #13 0x7aa770c3015a in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const zeek/src/packet_analysis/Analyzer.cc:120:25
    #14 0x7aa770c40293 in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) zeek/src/packet_analysis/Manager.cc:131:17
    #15 0x4e22cf in LLVMFuzzerTestOneInput zeek/src/fuzzers/packet-fuzzer.cc:39:22
    #16 0x4e9cab in main
    #17 0x7aa76d90e082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
    #18 0x41fbfd in _start

0x6070023d7cb7 is located 0 bytes to the right of 71-byte region [0x6070023d7c70,0x6070023d7cb7)
allocated by thread T0 here:
    #0 0x4dbf8d in operator new[](unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:98:3
    #1 0x7aa77235c8f5 in std::__1::__unique_if<unsigned char []>::__unique_array_unknown_bound std::__1::make_unique<unsigned char []>(unsigned long) /usr/local/include/c++/v1/__memory/unique_ptr.h:733:28
    #2 0x7aa77235c8f5 in zeek::detail::FuzzBuffer::Next() zeek/src/fuzzers/FuzzBuffer.cc:86:15
    #3 0x4e2462 in LLVMFuzzerTestOneInput zeek/src/fuzzers/packet-fuzzer.cc:27:19
    #4 0x4e9cab in main
```

**Comment by timwoj** [comment]
Fixed via 9af7d830e7d1bceb28d210a3a251fdfdddbe1659
