### ISSUE TITLE
Crash when using scripts compiled to C++

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3527]
While tinkering with silencing some warnings in the script_opt code, I ran into this crash at startup:

```
==40064==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x0001033e9a68 bp 0x00016dcf9d10 sp 0x00016dcf9ce0 T0)
==40064==The signal is caused by a READ memory access.
==40064==Hint: address points to the zero page.
    #0 0x1033e9a68 in std::__1::vector<zeek::IntrusivePtr<zeek::Type>, std::__1::allocator<zeek::IntrusivePtr<zeek::Type>>>::size[abi:v160006]() const vector:546
    #1 0x1048ef094 in zeek::IndexType::IndexType(zeek::TypeTag, zeek::IntrusivePtr<zeek::TypeList>, zeek::IntrusivePtr<zeek::Type>) Type.h:370
    #2 0x1048ee980 in zeek::TableType::TableType(zeek::IntrusivePtr<zeek::TypeList>, zeek::IntrusivePtr<zeek::Type>) Type.cc:461
    #3 0x104dc9960 in zeek::detail::CPPTableType::CPPTableType() RuntimeInitSupport.h:22
    #4 0x104dc9790 in zeek::detail::CPPTableType::CPPTableType() RuntimeInitSupport.h:22
    #5 0x104d925d0 in zeek::IntrusivePtr<zeek::detail::CPPTableType> zeek::make_intrusive<zeek::detail::CPPTableType>() IntrusivePtr.h:179
    #6 0x104d92474 in zeek::detail::CPP_TypeInits::PreInit(zeek::detail::InitsManager*, int, std::__1::vector<int, std::__1::allocator<int>>&) RuntimeInits.cc:247
    #7 0x104d91eb4 in zeek::detail::CPP_TypeInits::DoPreInits(zeek::detail::InitsManager*, std::__1::vector<int, std::__1::allocator<int>> const&) RuntimeInits.cc:228
    #8 0x1052db900 in zeek::detail::CPP_AbstractInits<zeek::IntrusivePtr<zeek::Type>, std::__1::vector<std::__1::vector<int, std::__1::allocator<int>>, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int>>>>>::InitializeCohort(zeek::detail::InitsManager*, int) RuntimeInits.h:146
    #9 0x1052d4f98 in zeek::detail::CPP_10019052985880183483ULL::finish_init__CPP() CPP-gen.cc:51465
    #10 0x105da86f4 in zeek::detail::use_CPP() ScriptOpt.cc:411
    #11 0x105da5bf8 in zeek::detail::analyze_scripts(bool) ScriptOpt.cc:581
    #12 0x1041325f4 in zeek::detail::setup(int, char**, zeek::Options*) zeek-setup.cc:928
    #13 0x106235a98 in main main.cc:52
    #14 0x18a5d7f24  (<unknown module>)
```

This is with running `gen-C++` with the default set of scripts (passing /dev/null), and running `use-C++` against $TRACES/http/get.trace.

**Comment by awelzel** [comment]
I believe this was fixed by https://github.com/zeek/zeek/pull/3546, closing.
