### ISSUE TITLE
Crashes due to Invalid Pointer Read in RE_Match_State::Match with ICMP packets

### ISSUE THREAD

**Issue by ronny8360988** [zeek/zeek#3671]
### Bottom Line
Zeek happens to crash due to memory access violation when invoking zeek::detail::RE_Match_State::Match within ICMP Analyzer with an invalid packet length.

### Stack Trace
[0x0]   ntdll!ZwAlpcSendWaitReceivePort+0x14   0x7cbb8fd268   0x7ffedf355222   
[0x1]   ntdll!SendMessageToWERService+0x1ca   0x7cbb8fd270   0x7ffedf355009   
[0x2]   ntdll!ReportExceptionInternal+0xdd   0x7cbb8fd3d0   0x7ffede233ddc   
[0x3]   KERNEL32!WerpReportFaultInternal+0x3d8   0x7cbb8fdf40   0x7ffede2339ca   
[0x4]   KERNEL32!WerpReportFault+0xbe   0x7cbb8fe060   0x7ffedce955e0   
[0x5]   KERNELBASE!UnhandledExceptionFilter+0xbdb80   0x7cbb8fe0a0   0x7ffedf4046d5   
[0x6]   ntdll!RtlpThreadExceptionFilter+0x83   0x7cbb8fe1d0   0x7ffedf3eb4c6   
[0x7]   ntdll!RtlUserThreadStart$filt$0+0x94   0x7cbb8fe1d0   0x7ffedf3eb4c6   
[0x8]   ntdll!__C_specific_handler+0x96   0x7cbb8fe210   0x7ffedf3fff4f   
[0x9]   ntdll!RtlpExecuteHandlerForException+0xf   0x7cbb8fe280   0x7ffedf36eb64   
[0xa]   ntdll!RtlDispatchException+0x424   0x7cbb8fe2b0   0x7ffedf3ff82e   
[0xb]   ntdll!KiUserExceptionDispatch+0x2e   0x7cbb8fea00   0x7ff75ff1c8d2   
**[0xc]   zeek::detail::RE_Match_State::Match+0xe2   0x7cbb8ff1a0   0x7ff75ff140c6   
[0xd]   zeek::detail::RuleMatcher::Match+0xc6   0x7cbb8ff240   0x7ff75fb81e29   
[0xe]   zeek::packet_analysis::ICMP::ICMPSessionAdapter::MatchEndpoint+0x39   0x7cbb8ff340   0x7ff75fb83c43   
[0xf]   zeek::packet_analysis::ICMP::ICMPAnalyzer::DeliverPacket+0x503   0x7cbb8ff390   0x7ff75fb8f789**   
[0x10]   zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket+0x4a9   0x7cbb8ff450   0x7ff75fcddca5   
[0x11]   zeek::packet_analysis::Analyzer::ForwardPacket+0x295   0x7cbb8ff5f0   0x7ff75fb911ec   
[0x12]   zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket+0x8dc   0x7cbb8ff6d0   0x7ff75fcddca5   
[0x13]   zeek::packet_analysis::Analyzer::ForwardPacket+0x295   0x7cbb8ff7d0   0x7ff75fb94962   
[0x14]   zeek::packet_analysis::IEEE802_11::IEEE802_11Analyzer::AnalyzePacket+0x122   0x7cbb8ff8b0   0x7ff75fcddca5   
[0x15]   zeek::packet_analysis::Analyzer::ForwardPacket+0x295   0x7cbb8ff8f0   0x7ff75fcdb875   
[0x16]   zeek::packet_analysis::Manager::ProcessPacket+0x185   0x7cbb8ff9d0   0x7ff75ff0ed18   
[0x17]   zeek::run_state::detail::dispatch_packet+0x348   0x7cbb8ffb50   0x7ff75fd34b44   
[0x18]   zeek::iosource::PktSrc::Process+0x24   0x7cbb8ffc00   0x7ff75ff0f5b8   
[0x19]   zeek::run_state::detail::run_loop+0x128   0x7cbb8ffc30   0x7ff76047c894   

### Root Cause
The "len" parameter passed by ICMPAnalyzer::DeliverPacket to zeek::detail::RE_Match_State::Match at [ICMP.cc:](https://github.com/zeek/zeek/blob/da0c1ca089660e8a0a496211e48d79c779cc2f4d/src/packet_analysis/protocol/icmp/ICMP.cc#L120) with the pointer "data" is too high:
`adapter->MatchEndpoint(data, len, is_orig);
`
Then, at [zeek::detail::RE_Match_State::Match](https://github.com/zeek/zeek/blob/master/src/RE.cc#L317) the crash happens when reading out of bounds ("bv" is "data"):
`ec = ecs[*(bv++)];
`

"len" and "data" are read from the IP header of the packet ([ICMP.cc](https://github.com/zeek/zeek/blob/da0c1ca089660e8a0a496211e48d79c779cc2f4d/src/packet_analysis/protocol/icmp/ICMP.cc#L61)):
```
const u_char* data = pkt->ip_hdr->Payload();
int len = pkt->ip_hdr->PayloadLen();
```

In the memory dump collected from one of the crashes, the value of "len" is 106:
![image](https://github.com/zeek/zeek/assets/111224127/cad8b997-718a-423b-9d31-f9ac030693ca)

However, "data" points to address 0x000002335e6c5f9e, and we can see that the actual length allocated at this address is less than 106 (0x6a):
![image](https://github.com/zeek/zeek/assets/111224127/c8bf9475-fedb-4a69-8163-2231d71b6ee5)

![image](https://github.com/zeek/zeek/assets/111224127/068117c5-268f-4971-a527-fe5d21906803)

### Resolution
ICMP Analyzer should generate a "weird" when the packet's payload size from the IP header is larger than the actual size of the packet's payload.

**Comment by timwoj** [comment]
Thank you for the report! Do you happen to have a pcap file that triggers it? We can certainly create one, but if you have one already it would make getting a fix out easier.

**Comment by ronny8360988** [comment]
Thank you!
Undortunately, I don't have any. 
In my team, we use Zeek as part of our network analysis software. The stack trace and the memory dumps were collected from clients who use our product

**Comment by timwoj** [comment]
If you don't mind, can you ping me on the Zeek slack? I have some questions about data from the crash dump that might be easier to work through in real time.

**Comment by ronny8360988** [comment]
Following a discussion on Zeek Slack, attaching more info regarding the memory dump.

The value of `remaining` in the mentioned dump is 66(0x42), after the reduction by 8 that happens at `ICMPAnalyzer::DeliverPacket`. Seems like this is a valid value, as seen in the following screen shot:
![image](https://github.com/zeek/zeek/assets/111224127/297e0a7a-e27a-41a5-bf25-9f3a1b1322c7)

Snapshot of all local variables:
![image](https://github.com/zeek/zeek/assets/111224127/da36f845-5cc4-4ff4-9965-175eba0b2a71)

**Comment by timwoj** [comment]
We do have a couple of fixes we made for ICMP length handling. You can check if they're in your tree: 56f9110ec and 94ee83739

If you can get it, can we see the full packet data from the `pkt->data` field in the screenshots above? That would let me recreate the packet manually and see if I can reproduce it.

**Comment by ronny8360988** [comment]
Thank you. These commits are indeed in the tree.

Here's the content of `pkt->data` (address 0x000002335e6c5f60):

0:003> db 0x000002335e6c5f60 L0xa8
000002335e6c5f60  88 42 30 00 30 24 32 cd-28 cd 18 4b 0d 38 d8 a8  .B0.0$2.(..K.8..
000002335e6c5f70  3c 41 0e 90 70 75 80 a5-06 00 aa aa 03 00 00 00  <A..pu..........
000002335e6c5f80  08 00 45 c0 00 86 a6 d8-00 00 3f 01 8c 23 c0 a8  ..E.......?..#..
000002335e6c5f90  e4 65 c0 a8 e2 04 03 03-45 20 00 00 00 00 45 00  .e......E ....E.
000002335e6c5fa0  00 6a e7 95 00 00 7f 11-0c 32 c0 a8 e2 04 c0 a8  .j.......2......
000002335e6c5fb0  e4 65 e5 83 00 a1 00 56-81 6d 30 4c 02 01 00 04  .e.....V.m0L....
000002335e6c5fc0  06 70 75 62 6c 69 63 a0-3f 02 02 7a 63 02 01 00  .public.?..zc...
000002335e6c5fd0  02 01 00 30 33 30 0f 06-0b 2b 06 01 02 01 19 03  ...030...+......
000002335e6c5fe0  00 00 00 00 00 00 00 00-b0 1d 6e 5e 33 02 00 00  ..........n^3...
000002335e6c5ff0  30 b3 04 5c 33 02 00 00-00 00 00 00 00 00 00 00  0..\3...........
000002335e6c6000  ?? ?? ?? ?? ?? ?? ?? ??                          ????????


![image](https://github.com/zeek/zeek/assets/111224127/309a5697-2f09-442f-bc39-81febde5bceb)



![image](https://github.com/zeek/zeek/assets/111224127/596ad90a-92dd-4f28-8955-f4e1145e7a7d)

**Comment by JustinAzoff** [comment]
This reminds me of https://github.com/zeek/zeek/issues/1751

As a custom PktSrc is in use here, I'd suspect that may be where the issue lies.

**Comment by timwoj** [comment]
I'm somewhat confused by the packet data to be honest. As decoded by the ethernet packet analyzer, `l2_src` and `l2_dst`should be the first 6 bytes and the second 6 bytes. That would make l2_src start with 0x88, but that's not the case here. Plus, the two addresses given for `l2_src` and `l2_dst` are separated by 12 bytes, not 6. I confirmed that it's working the way I'd expect with a couple of ICMP packets captured from my local network.

Is there a custom packet analyzer is place here for handling the ethernet frame? Is this tunneled data of some sort? I'm just trying to figure out how that data even get through the ethernet analyzer without getting thrown away.

**Comment by ckreibich** [comment]
There's some meaningful Ethernet info in that blob but I can't quite make sense of it. When you skip 20 bytes into the frame, it looks like a regular Ethernet II frame followed by IP and ICMP (truncated), see here:

[ethernet.pcap.zip](https://github.com/zeek/zeek/files/15018423/ethernet.pcap.zip)

The MAC addresses look suspect there though (aa:aa:03:00:00:00?), so I don't think that's quite right. The earlier bytes look kind of meaningful as an 802.3 header. Hypothetically:
```
0d:38:d8:a8:3c:41 destination mac
0e:90:70:75:80:a5 source mac
06:00             size
aa                dsap
aa                ssap
03                control field
00:00:00          SNAP vendor code
08:00             ethertype IP
```
... except size would be 0x0600 = 1536, and that's exactly the threshold from which on afaict the size is not a size, but to be interpreted as ethertype. I'm guessing I'm off with all of this — I see 802.11 in the original backtrace so maybe there's a better interpretation in there based on it? I don't speak fluent 802.11. :-)

**Comment by ckreibich** [comment]
I learned some 802.11 and have interesting news.

The whole frame is indeed 802.11. I changed the capture type of the pcap to `DLT_IEEE802_11`, at which point the header starts looking meaningful in Wireshark (for example, vendors for the three MAC addresses are Intel, Ruckus, Cisco), but since the protected-frame bit is set in the frame control bytes, the rest is off (Wireshark looks for encryption info, and doesn't find the right entry point to the IP header).

If I just clear that encryption bit, the whole packet starts to look like in the backtrace, including a truncated ICMP packet. 

This ZIP contains the two pcaps, one with just the DLT changed (mspacket-80211.pcap), the other with the protected bit cleared (mspacket-80211-protected-cleared.pcap):

[mspacket-80211.zip](https://github.com/zeek/zeek/files/15046252/mspacket-80211.zip)

Questions now: do any Zeeks crash on that packet (I haven't yet tried), and why does the raw frame indicate encryption when Zeek would not be able to process it as-is — a likely explanation would be that the 802.11 analyzer has been modified.

```
$ tshark -V -r mspacket-80211-protected-cleared.pcap
Frame 1: 160 bytes on wire (1280 bits), 160 bytes captured (1280 bits)
    Encapsulation type: IEEE 802.11 Wireless LAN (20)
    Arrival Time: Apr 16, 2024 15:42:12.091910000 PDT
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1713307332.091910000 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 160 bytes (1280 bits)
    Capture Length: 160 bytes (1280 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: wlan:llc:ip:icmp:ip:udp:data]
IEEE 802.11 QoS Data, Flags: ......F.
    Type/Subtype: QoS Data (0x0028)
    Frame Control Field: 0x8802
        .... ..00 = Version: 0
        .... 10.. = Type: Data frame (2)
        1000 .... = Subtype: 8
        Flags: 0x02
            .... ..10 = DS status: Frame from DS to a STA via AP(To DS: 0 From DS: 1) (0x2)
            .... .0.. = More Fragments: This is the last fragment
            .... 0... = Retry: Frame is not being retransmitted
            ...0 .... = PWR MGT: STA will stay up
            ..0. .... = More Data: No data buffered
            .0.. .... = Protected flag: Data is not protected
            0... .... = +HTC/Order flag: Not strictly ordered
    .000 0000 0011 0000 = Duration: 48 microseconds
    Receiver address: IntelCor_cd:28:cd (30:24:32:cd:28:cd)
    Transmitter address: RuckusWi_38:d8:a8 (18:4b:0d:38:d8:a8)
    Destination address: IntelCor_cd:28:cd (30:24:32:cd:28:cd)
    Source address: Cisco_90:70:75 (3c:41:0e:90:70:75)
    BSS Id: RuckusWi_38:d8:a8 (18:4b:0d:38:d8:a8)
    STA address: IntelCor_cd:28:cd (30:24:32:cd:28:cd)
    .... .... .... 0000 = Fragment number: 0
    1010 0101 1000 .... = Sequence number: 2648
    Qos Control: 0x0006
        .... .... .... 0110 = TID: 6
        [.... .... .... .110 = Priority: Voice (Voice) (6)]
        .... .... ...0 .... = EOSP: Service period
        .... .... .00. .... = Ack Policy: Normal Ack (0x0)
        .... .... 0... .... = Payload Type: MSDU
        0000 0000 .... .... = QAP PS Buffer State: 0x00
            .... ..0. .... .... = Buffer State Indicated: No
Logical-Link Control
    DSAP: SNAP (0xaa)
        1010 101. = SAP: SNAP
        .... ...0 = IG Bit: Individual
    SSAP: SNAP (0xaa)
        1010 101. = SAP: SNAP
        .... ...0 = CR Bit: Command
    Control field: U, func=UI (0x03)
        000. 00.. = Command: Unnumbered Information (0x00)
        .... ..11 = Frame type: Unnumbered frame (0x3)
    Organization Code: 00:00:00 (Officially Xerox, but
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 192.168.228.101, Dst: 192.168.226.4
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0xc0 (DSCP: CS6, ECN: Not-ECT)
        1100 00.. = Differentiated Services Codepoint: Class Selector 6 (48)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 134
        [Expert Info (Error/Protocol): IPv4 total length exceeds packet length (126 bytes)]
            [IPv4 total length exceeds packet length (126 bytes)]
            [Severity level: Error]
            [Group: Protocol]
    Identification: 0xa6d8 (42712)
    000. .... = Flags: 0x0
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 63
    Protocol: ICMP (1)
    Header Checksum: 0x8c23 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 192.168.228.101
    Destination Address: 192.168.226.4
Internet Control Message Protocol
    Type: 3 (Destination unreachable)
    Code: 3 (Port unreachable)
    Checksum: 0x4520 incorrect, should be 0x4741
        [Expert Info (Warning/Checksum): Bad checksum [should be 0x4741]]
            [Bad checksum [should be 0x4741]]
            [Severity level: Warning]
            [Group: Checksum]
    [Checksum Status: Bad]
    Unused: 00000000
    Internet Protocol Version 4, Src: 192.168.226.4, Dst: 192.168.228.101
        0100 .... = Version: 4
        .... 0101 = Header Length: 20 bytes (5)
        Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
            0000 00.. = Differentiated Services Codepoint: Default (0)
            .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
        Total Length: 106
        Identification: 0xe795 (59285)
        000. .... = Flags: 0x0
            0... .... = Reserved bit: Not set
            .0.. .... = Don't fragment: Not set
            ..0. .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment Offset: 0
        Time to Live: 127
        Protocol: UDP (17)
        Header Checksum: 0x0c32 [validation disabled]
        [Header checksum status: Unverified]
        Source Address: 192.168.226.4
        Destination Address: 192.168.228.101
    User Datagram Protocol, Src Port: 58755, Dst Port: 161
        Source Port: 58755
        Destination Port: 161
        Length: 86
        Checksum: 0x816d [unverified]
        [Checksum Status: Unverified]
        [Stream index: 0]
        UDP payload (70 bytes)
Data (70 bytes)

0000  30 4c 02 01 00 04 06 70 75 62 6c 69 63 a0 3f 02   0L.....public.?.
0010  02 7a 63 02 01 00 02 01 00 30 33 30 0f 06 0b 2b   .zc......030...+
0020  06 01 02 01 19 03 00 00 00 00 00 00 00 00 b0 1d   ................
0030  6e 5e 33 02 00 00 30 b3 04 5c 33 02 00 00 00 00   n^3...0..\3.....
0040  00 00 00 00 00 00                                 ......
    Data: 304c02010004067075626c6963a03f02027a630201000201003033300f060b2b06010201…
    [Length: 70]
```

**Comment by ckreibich** [comment]
I see now how this crash can happen. First, another tweak to the pcap: the wire length of that IP packet is 168 bytes, but the captured part is 160 (ten rows in the above hex dumps — easy to track — and aligning with the 8 bytes of `??` in the screenshot, as well as the actual packet header data). This pcap has this property:

[mspacket-80211-protected-cleared-caplen-fixed.pcap.zip](https://github.com/zeek/zeek/files/15084141/mspacket-80211-protected-cleared-caplen-fixed.pcap.zip)

(This flags another mystery in your data @ronny8360988 — the caplen in your screenshot says 0x80, 128, so even shorter. I can't explain that since your packet actually has more data than that. Could indeed be something buggy in your packet source?)

When Zeek enters `ICMPAnalyzer::DeliverPacket()`, the input arguments have correct values: `remaining=106`, `pkt->len=168`, `pkt->cap_len=160`. I think the bug is [here](https://github.com/zeek/zeek/blob/master/src/packet_analysis/protocol/icmp/ICMP.cc#L62-L66): we grab `len` from the packet header (that's 114), and only override it with `remaining` when the returned value is 0.

We then adjust `data`, `remaining`, and `len` by 8 [further down](https://github.com/zeek/zeek/blob/master/src/packet_analysis/protocol/icmp/ICMP.cc#L95-L98) to skip the ICMP header, but `len` remains too high ... and gets passed as such into a few other places, including `adapter->MatchEndpoint(data, len, is_orig)`. Whether this triggers a crash in the regex code depends on two things: (1) the regex in question, since the state machine must provide sufficient transitions for the `bv++` to reach the undefined range, (2) whether there's legit data in that range. I modified the regex code to simply keep advancing through the buffer, and while you can see that the buffer content does change into invalid content, Zeek _still_ doesn't crash — perhaps because the snaplen in the pcap is much larger.

The fix is likely to use the minimum of `len` and `remaining`, [as we do e.g. in UDP](https://github.com/zeek/zeek/blob/master/src/packet_analysis/protocol/udp/UDP.cc#L200-L203).

**Comment by JustinAzoff** [comment]
@ckreibich if you apply this patch it may crash with asan enabled:

```
--- a/src/iosource/pcap/Source.cc
+++ b/src/iosource/pcap/Source.cc
@@ -240,7 +240,7 @@ bool PcapSource::ExtractNextPacket(Packet* pkt) {
         default: reporter->InternalError("unhandled pcap_next_ex return value: %d", res); return false;
     }
 
-    pkt->Init(props.link_type, &header->ts, header->caplen, header->len, data);
+    pkt->Init(props.link_type, &header->ts, header->caplen, header->len, data, true);
 
     if ( header->len == 0 || header->caplen == 0 ) {
         Weird("empty_pcap_header", pkt);
```

That `copy` argument to `Init` makes zeek do

```
        data = new u_char[arg_caplen];
        memcpy(const_cast<u_char*>(data), arg_data, arg_caplen);
```

which makes the packet buffer exactly the supposed size of the packet.

**Comment by ckreibich** [comment]
Thanks Justin! I put together a reproducer with a rule with sufficient state transitions and yet another tweaked pcap, this one having a snaplen that matches the truncated packet, so the buffer's now short enough:
```
$ zeek --version
zeek version 7.0.0-dev.147-debug
$ zeek -s ./test.sig -r ~/mspacket-80211-protected-cleared-caplen-fixed-snaplen-fixed.pcap
=================================================================
==1578682==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60e000301660 at pc 0x000002234afb bp 0x7fff16a4c090 sp 0x7fff16a4c088
READ of size 1 at 0x60e000301660 thread T0
    #0 0x2234afa in zeek::detail::RE_Match_State::Match(unsigned char const*, int, bool, bool, bool) /home/christian/devel/zeek/zeek/src/RE.cc:318
    #1 0x2257096 in zeek::detail::RuleMatcher::Match(zeek::detail::RuleEndpointState*, zeek::detail::Rule::PatternType, unsigned char const*, int, bool, bool, bool) /home/christian/devel/zeek/zeek/src/RuleMatcher.cc:806
    #2 0x225aabc in zeek::detail::RuleMatcherState::Match(zeek::detail::Rule::PatternType, unsigned char const*, int, bool, bool, bool, bool) /home/christian/devel/zeek/zeek/src/RuleMatcher.cc:1300
    #3 0x1504ea3 in zeek::packet_analysis::ICMP::ICMPSessionAdapter::MatchEndpoint(unsigned char const*, int, bool) /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/icmp/ICMPSessionAdapter.cc:67
    #4 0x14fc824 in zeek::packet_analysis::ICMP::ICMPAnalyzer::DeliverPacket(zeek::Connection*, double, bool, int, zeek::Packet*) /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/icmp/ICMP.cc:120
    #5 0x14b5e1c in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc:88
    #6 0x14607a5 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const /home/christian/devel/zeek/zeek/src/packet_analysis/Analyzer.cc:117
    #7 0x14ae362 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/ip/IP.cc:265
    #8 0x14607a5 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const /home/christian/devel/zeek/zeek/src/packet_analysis/Analyzer.cc:117
    #9 0x149060b in zeek::packet_analysis::IEEE802_11::IEEE802_11Analyzer::HandleInnerPacket(unsigned long, unsigned char const*, zeek::Packet*) const /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/ieee802_11/IEEE802_11.cc:162
    #10 0x14909a1 in zeek::packet_analysis::IEEE802_11::IEEE802_11Analyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) /home/christian/devel/zeek/zeek/src/packet_analysis/protocol/ieee802_11/IEEE802_11.cc:84
    #11 0x14607a5 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const /home/christian/devel/zeek/zeek/src/packet_analysis/Analyzer.cc:117
    #12 0x146e7cd in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) /home/christian/devel/zeek/zeek/src/packet_analysis/Manager.cc:116
    #13 0x2262f4d in zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*) /home/christian/devel/zeek/zeek/src/RunState.cc:242
    #14 0x1867722 in zeek::iosource::PktSrc::Process() /home/christian/devel/zeek/zeek/src/iosource/PktSrc.cc:120
    #15 0x2264b81 in zeek::run_state::detail::run_loop() /home/christian/devel/zeek/zeek/src/RunState.cc:289
    #16 0x7b9181 in main /home/christian/devel/zeek/zeek/src/main.cc:93
    #17 0x7fb274046149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #18 0x7fb27404620a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #19 0x7b8c34 in _start (/home/christian/inst/opt/zeek/bin/zeek+0x7b8c34) (BuildId: 01f1c570cd918202a3a79c1d40f00dc62eba3b63)

0x60e000301660 is located 0 bytes after 160-byte region [0x60e0003015c0,0x60e000301660)
allocated by thread T0 here:
    #0 0x7fb27e0d92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 2b657470ea196ba4342e3bd8a3cc138b1e200599)
    #1 0x7fb27e6d017f in pcap_check_header (/lib64/libpcap.so.1+0x2a17f) (BuildId: b2c27ef72665c5895f38a2abd1ea7e63b2962439)
    #2 0x7fb27e6d0ea4 in pcap_fopen_offline_with_tstamp_precision (/lib64/libpcap.so.1+0x2aea4) (BuildId: b2c27ef72665c5895f38a2abd1ea7e63b2962439)
    #3 0x186d971 in zeek::iosource::pcap::PcapSource::OpenOffline() /home/christian/devel/zeek/zeek/src/iosource/pcap/Source.cc:183
    #4 0x186df87 in zeek::iosource::pcap::PcapSource::Open() /home/christian/devel/zeek/zeek/src/iosource/pcap/Source.cc:34
    #5 0x18664db in zeek::iosource::PktSrc::InitSource() /home/christian/devel/zeek/zeek/src/iosource/PktSrc.cc:97
    #6 0x1852339 in zeek::iosource::Manager::Register(zeek::iosource::IOSource*, bool, bool) /home/christian/devel/zeek/zeek/src/iosource/Manager.cc:331
    #7 0x185267e in zeek::iosource::Manager::Register(zeek::iosource::PktSrc*) /home/christian/devel/zeek/zeek/src/iosource/Manager.cc:345
    #8 0x1856fdf in zeek::iosource::Manager::OpenPktSrc(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/christian/devel/zeek/zeek/src/iosource/Manager.cc:401
    #9 0x2265343 in zeek::run_state::detail::init_run(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool) /home/christian/devel/zeek/zeek/src/RunState.cc:170
    #10 0x1dfd153 in zeek::detail::setup(int, char**, zeek::Options*) /home/christian/devel/zeek/zeek/src/zeek-setup.cc:937
    #11 0x7b8e43 in main /home/christian/devel/zeek/zeek/src/main.cc:52
    #12 0x7fb274046149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #13 0x7fb27404620a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
    #14 0x7b8c34 in _start (/home/christian/inst/opt/zeek/bin/zeek+0x7b8c34) (BuildId: 01f1c570cd918202a3a79c1d40f00dc62eba3b63)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/christian/devel/zeek/zeek/src/RE.cc:318 in zeek::detail::RE_Match_State::Match(unsigned char const*, int, bool, bool, bool)
Shadow bytes around the buggy address:
  0x60e000301380: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x60e000301400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x60e000301480: 00 00 00 fa fa fa fa fa fa fa fa fa 00 00 00 00
  0x60e000301500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x60e000301580: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x60e000301600: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
  0x60e000301680: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x60e000301700: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x60e000301780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x60e000301800: 00 00 00 00 fa fa fa fa fa fa fa fa fd fd fd fd
  0x60e000301880: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1578682==ABORTING
```
[reproducer.zip](https://github.com/zeek/zeek/files/15102178/reproducer.zip)

**Comment by JustinAzoff** [comment]
Super cool.  We've definitely had some issues over the years where something was obviously wrong, but the behavior of pcap libraries of reusing existing large buffers for small packets has meant that small digit number of out of bounds byte reads have been really hard to track down.

Any ideas with the existing packet-fuzzer never found this?  Was it missing the right sig to trigger this?  Maybe we need to add some IEEE802_11 files to the corpus?

**Comment by ckreibich** [comment]
Tim and I were wondering too. At the end of the day this wasn't about 802.11 at all, it's really just that a caplen of less than the full packet wasn't honored in some ICMP code.

It would be nice to fuzz packets more specifically — or perhaps even just iterate through forced caplens on our existing test traffic.

**Comment by ckreibich** [comment]
I've added this to the 6.0.4 / 6.2.1 backport lists, fyi.

**Comment by JustinAzoff** [comment]
Ah, I think that explains why.. if you look at the packet fuzzer:

https://github.com/zeek/zeek/blob/9a158b3c9cffe5e9c240a4ef372689b8132b955d/src/fuzzers/packet-fuzzer.cc#L32

We always initialize the packet with exactly the right size for both length and cap length.

Should we also have a version that sets these to different values to test truncated packets?

**Comment by ckreibich** [comment]
> Should we also have a version that sets these to different values to test truncated packets?

Certainly seems worth a try to me, yeah. It's interesting because the details matter — for example, a truncation that cuts a fixed packet header might not crash, but one that cuts off in the middle of payload might.
