### ISSUE TITLE
Crash 6.2.0 : Flare.cc: zeek::detail::bad_pipe_op 

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#3682]
I have been seeing intermittent crashes in 6.2.0 with the following coredump:

For reference: 
```
(gdb) bt
#0  0x0000000803888bca in thr_kill () from /lib/libc.so.7
#1  0x0000000803886f94 in raise () from /lib/libc.so.7
#2  0x00000008037ff489 in abort () from /lib/libc.so.7
#3  0x0000000000cec2d1 in zeek::Reporter::FatalErrorWithCore (this=<optimized out>, fmt=<optimized out>) at /usr/local/src/zeek-6.0.1/src/Reporter.cc:154
#4  0x0000000000c8966f in zeek::detail::bad_pipe_op (which=0x4d1b9d "read", signal_safe=<optimized out>) at /usr/local/src/zeek-6.0.1/src/Flare.cc:76
#5  0x0000000000c896d5 in zeek::detail::Flare::Extinguish (this=0x8a4558ca4, signal_safe=false) at /usr/local/src/zeek-6.0.1/src/Flare.cc:153
#6  0x0000000000d9a04b in zeek::threading::MsgThread::Process (this=0x8a4558800) at /usr/local/src/zeek-6.0.1/src/threading/MsgThread.cc:517
#7  0x0000000000d16ed6 in zeek::run_state::detail::run_loop () at /usr/local/src/zeek-6.0.1/src/RunState.cc:349
#8  0x00000000007506c8 in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/zeek-6.0.1/src/main.cc:102
```

I'll try to see how I can replicate it - so far different physical clusters have showing this crash - albeit very intermittent - I don't see a predictive pattern yet!

**Comment by leres** [comment]
I'm seeing similar crashes with 6.0.3 (standalone):
```
(gdb) bt
#0  0x000000082e80841a in thr_kill () from /lib/libc.so.7
#1  0x000000082e781e64 in raise () from /lib/libc.so.7
#2  0x000000082e8326f9 in abort () from /lib/libc.so.7
#3  0x0000000000fb863f in zeek::Reporter::FatalErrorWithCore(char const*, ...) ()
#4  0x0000000000f5150a in zeek::detail::bad_pipe_op(char const*, bool) ()
#5  0x0000000000f51576 in zeek::detail::Flare::Extinguish(bool) ()
#6  0x000000000106c92b in zeek::threading::MsgThread::Process() ()
#7  0x0000000000fe46d6 in zeek::run_state::detail::run_loop() ()
#8  0x00000000012542f1 in main () 
```
Unfortunately I did not have debugging symbols enabled (I do now).

**Comment by timwoj** [comment]
> I'm seeing similar crashes with 6.0.3 (standalone):

Dang, I was really hoping this was something specific to 6.2.

**Comment by leres** [comment]
I had my first crash since building with debugging symbols (RELWITHDEBINFO) but I'm not sure that it's related:
```
(gdb) bt
#0  0x000000082e63041a in ?? ()
#1  0x000000082e5a9e64 in ?? ()
#2  0x0000000000018d19 in ?? ()
#3  0xfd1399c053131912 in ?? ()
#4  0x00000008219cabe4 in ?? ()
#5  0x00000008376490a4 in ?? ()
#6  0x00000008219cac00 in ?? ()
#7  0x000000082e65a6f9 in ?? ()
#8  0x0000000832d3e000 in ?? ()
#9  0x000000082e6d61f0 in ?? ()
#10 0xffffffdf2e6d61f0 in ?? ()
#11 0xffffffffffffffff in ?? ()
#12 0x00000008ffffffff in ?? ()
#13 0x00000000006d6bf0 in ?? ()
#14 0x00000008219cace0 in ?? ()
#15 0x0000000000f7b1f1 in zeek::Reporter::FatalErrorWithCore (
    this=<optimized out>, fmt=<optimized out>)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/Reporter.cc:154
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
The fatal error was:
```
May  5 01:37:14 fatal error: unexpected pipe read failure: Bad file descriptor
```

**Comment by leres** [comment]
I lied, I see now I had crash a week ago that looks related to this problem:
```
(gdb) bt
#0  0x000000082caec41a in thr_kill () from /lib/libc.so.7
#1  0x000000082ca65e64 in raise () from /lib/libc.so.7
#2  0x000000082cb166f9 in abort () from /lib/libc.so.7
#3  0x0000000000f7b1f1 in zeek::Reporter::FatalErrorWithCore (
    this=<optimized out>, fmt=<optimized out>)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/Reporter.cc:154
#4  0x0000000000f186cf in zeek::detail::bad_pipe_op (which=0x6d6bf0 "read", 
    signal_safe=<optimized out>)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/Flare.cc:76
#5  0x0000000000f18735 in zeek::detail::Flare::Extinguish (this=0x870dbdca4, 
    signal_safe=false)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/Flare.cc:153
#6  0x00000000010287fb in zeek::threading::MsgThread::Process (
    this=0x870dbd800)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/threading/MsgThread.cc:517
#7  0x0000000000fa5906 in zeek::run_state::detail::run_loop ()
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/RunState.cc:349
#8  0x00000000011fe1de in main (argc=<optimized out>, argv=<optimized out>)
    at /wrkdirs/usr/ports/security/zeek/work/zeek-6.0.3/src/main.cc:102
```
And the log says:
```
May  5 01:37:14 fatal error: unexpected pipe read failure: Bad file descriptor
```
(The same error as today so maybe that was related but the stack got trashed...)

So maybe the process on the other end of the pipe is gone and EBADF should not be fatal?

 Happy to make files available for analysis (note that the debugging symbol zeek is quite large...)

**Comment by awelzel** [comment]
I don't quite know how to fix this yet, but I'll assign myself for now.
