### ISSUE TITLE
Segfault in zeek 7 with JavaScript support under alpine

### ISSUE THREAD

**Issue by timo-mue** [zeek/zeek#3978]
Hello,

I have a Docker image based on alpine that includes a Zeek installation. When processing trace files with a script that loads some JavaScript code and only after Zeek is already running for a few seconds there is a segfault when the stream of trace files is interrupted.
To recreate this behavior I tried to reduce the Docker image to the relevant components and run a script that creates a named pipe which Zeek is reading from while running a script that is empty but ends on `.js` to initialize the Node.js environment/JavaScript engine. After running for 10 seconds a pcap-header with no following packet records is written to the pipe with `cat`
 which closes the pipe afterwards and should lead to Zeek ending normally but causes a segfault instead.

This is the Dockerfile:
```dockerfile
FROM alpine:3.20

RUN apk add --no-cache \
    make \
    g++ \
    python3-dev \
    linux-headers \
    openssl-dev \
    libpcap-dev \
    zlib-dev \
    fts-dev \
    cmake \
    clang \
    bison \
    bash \
    swig \
    flex \
    flex-dev \
    flex-libs \
    nodejs-dev \
    nodejs-libs

WORKDIR /build
RUN wget --quiet -O /build/zeek.tar.gz "https://github.com/zeek/zeek/releases/download/v7.0.3/zeek-7.0.3.tar.gz" \
    && tar xf /build/zeek.tar.gz

WORKDIR /build/zeek-7.0.3

# Fix PAGE_SIZE already being defined as macro
RUN sed -i '147a#ifdef PAGE_SIZE\n#undef PAGE_SIZE\n#endif' auxil/spicy/3rdparty/fiber/src/fiber.c

RUN ./configure --build-type=Debug \
    && make -j 4 \
    && make install

ENV PATH $PATH:/usr/local/zeek/bin

WORKDIR /test

COPY runZeek.sh /test/runZeek.sh
CMD ["/test/runZeek.sh"]
```

And this is the `runZeek.sh` script:
```bash
#!/bin/sh
set -x
mkfifo pipe
touch empty.js
echo -n "1MOyoQIABAAAAAAAAAAAAA0AAQABAAAA" | base64 -d > header.pcap
ulimit -c unlimited
CORE_PATTERN="$(cat /proc/sys/kernel/core_pattern)"
CORE_DIR=${CORE_PATTERN%/*}
mkdir -p $CORE_DIR
zeek -b -C -r pipe empty.js &
sleep 10
cat header.pcap > pipe
wait
ls -lh $CORE_DIR
```

Inspecting a coredump reveales that the segfault is caused by the libnode library and running the script above with the official Docker image or a self compiled zeek version under ubuntu doesn't lead to a segfault but I am kinda restricted to alpine images.

**Comment by awelzel** [comment]
Hey @timo-mue - awesome reproducer, thank you!

I've compiled the same version of Node.js used in the Alpine image (v20.15.1) on Ubuntu 24.04 and observe the same crash.
```
AddressSanitizer:DEADLYSIGNAL                                                                                                                                                                 =================================================================                              
==229353==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000c0 (pc 0x7fa9c0950ce8 bp 0x7ffd6ae44360 sp 0x7ffd6ae44330 T0)
==229353==The signal is caused by a READ memory access.                                        
==229353==Hint: address points to the zero page.                                               
    #0 0x7fa9c0950ce8 in v8::internal::WriteBarrier::CombinedBarrierFromInternalFields(v8::internal::JSObject, unsigned long, void**) ../../deps/v8/src/heap/heap-write-barrier-inl.h:345
    #1 0x7fa9c0950ce8 in v8::internal::WriteBarrier::CombinedBarrierFromInternalFields(v8::internal::JSObject, void*) ../../deps/v8/src/heap/heap-write-barrier-inl.h:333
    #2 0x7fa9c0950ce8 in v8::Object::SetAlignedPointerInInternalField(int, void*) ../../deps/v8/src/api/api.cc:6389
    #3 0x7fa9c0002785 in node::BaseObject::~BaseObject() ../../src/base_object.cc:43           
    #4 0x7fa9c0002785 in node::BaseObject::~BaseObject() ../../src/base_object.cc:25           
    #5 0x7fa9c008b114 in node::loader::ModuleWrap::~ModuleWrap() ../../src/module_wrap.cc:84   
    #6 0x7fa9c001e15f in node::CleanupQueue::Drain() ../../src/cleanup_queue.cc:37             
    #7 0x7fa9c018f5fd in node::Realm::RunCleanup() ../../src/node_realm.cc:218                 
    #8 0x7fa9c004b8eb in node::Environment::RunCleanup() ../../src/env.cc:1214                 
    #9 0x7fa9bffe8601 in node::FreeEnvironment(node::Environment*) ../../src/api/environment.cc:511
    #10 0x7fa9c69afe13 in std::unique_ptr<node::Environment, void (*)(node::Environment*)>::~unique_ptr() /usr/include/c++/13/bits/unique_ptr.h:404
    #11 0x7fa9c69be21d in plugin::Nodejs::Instance::~Instance() /home/awelzel/corelight-oss/zeekjs/src/Nodejs.h:24 
    #12 0x7fa9c69bd11d in plugin::Corelight_ZeekJS::Plugin::Done() /home/awelzel/corelight-oss/zeekjs/src/Plugin.cc:397
    #13 0x55e1c6046f3e in zeek::plugin::Manager::FinishPlugins() /home/awelzel/corelight-oss/zeek/src/plugin/Manager.cc:492
    #14 0x55e1c592e8bb in terminate_zeek /home/awelzel/corelight-oss/zeek/src/zeek-setup.cc:384                            
    #15 0x55e1c592f4ba in zeek::detail::cleanup(bool) /home/awelzel/corelight-oss/zeek/src/zeek-setup.cc:1060        
    #16 0x55e1c68981d7 in main /home/awelzel/corelight-oss/zeek/src/main.cc:113                                                                                                               
    #17 0x7fa9c742a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58                                                                                                    
    #18 0x7fa9c742a28a in __libc_start_main_impl ../csu/libc-start.c:360                                                                                                                      
    #19 0x55e1c3f6b404 in _start (/home/awelzel/corelight-oss/zeek/asan-build/src/zeek+0xd65404) (BuildId: e2eccb6343ff0226)
                                                                                                                                                                                              
AddressSanitizer can not provide additional info.                                                                                                                                             
SUMMARY: AddressSanitizer: SEGV ../../deps/v8/src/heap/heap-write-barrier-inl.h:345 in v8::internal::WriteBarrier::CombinedBarrierFromInternalFields(v8::internal::JSObject, unsigned long, vo
id**)   
```

No dice at the culprit yet though.
