### ISSUE TITLE
Logger node hanging in caf on terminate

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#519]
Issuing a zeekctl shutdown, the logger node hangs in caf:

```
# gdb ./bin/zeek 65791
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/zeek...bt
done.
Attaching to program: /srv/zeek/zeek/bin/zeek, process 65791
[New LWP 65792]
[New LWP 65793]
[New LWP 65794]
[New LWP 65795]
[New LWP 65796]
[New LWP 65797]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fbdff1009f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x564fb0646880) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) bt
#0  0x00007fbdff1009f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x564fb0646880) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x564fb0646830, cond=0x564fb0646858) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x564fb0646858, mutex=0x564fb0646830) at pthread_cond_wait.c:655
#3  0x00007fbdfe7f079c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fbdfebb289c in caf::actor_registry::await_running_count_equal (this=0x564fb0646828, expected=expected@entry=0)
    at /home/johanna/xxx-zeek/aux/broker/3rdparty/caf/libcaf_core/src/actor_registry.cpp:127
#5  0x00007fbdfebb505e in caf::actor_system::await_all_actors_done (this=<optimized out>)
    at /home/johanna/xxx-zeek/aux/broker/3rdparty/caf/libcaf_core/src/actor_system.cpp:424
#6  0x00007fbdfebb5cbd in caf::actor_system::~actor_system (this=0x564fb0645800, __in_chrg=<optimized out>)
    at /home/johanna/xxx-zeek/aux/broker/3rdparty/caf/libcaf_core/src/actor_system.cpp:311
#7  0x00007fbdff4d5727 in broker::endpoint::shutdown (this=0x564fb0645300) at /home/johanna/xxx-zeek/aux/broker/src/endpoint.cc:167
#8  0x0000564fad5bfed8 in bro_broker::Manager::Terminate (this=0x564faed1f450) at /home/johanna/xxx-zeek/src/broker/Manager.cc:241
#9  0x0000564fad269609 in terminate_bro () at /home/johanna/xxx-zeek/src/main.cc:340
#10 0x0000564fad269886 in termination_signal () at /home/johanna/xxx-zeek/src/main.cc:371
#11 0x0000564fad302fb5 in net_run () at /home/johanna/xxx-zeek/src/Net.cc:370
#12 0x0000564fad1b6186 in main (argc=<optimized out>, argv=<optimized out>) at /home/johanna/xxx-zeek/src/main.cc:1083
```

I think the same was true for the proxy - but I was not quick enough to prevent zeekctl from killing it.

**Comment by 0xxon** [comment]
I am not actually sure there is anything to be done here - I just wanted to record this because we are kind of close to a release. I will re-start it, and check in another day if this happens again...

**Comment by 0xxon** [comment]
Host is running Ubuntu 18.04.1 LTS.

gcc version:

```
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04)
``` 

Version of zeek running was 1a7f14dab; I just updated it to b3884de2e530ae3f54d9f95faee30c8c9fcbe4fd

**Comment by 0xxon** [comment]
I was not able to reproduce this on this system after the update to b3884de - closing for the moment.
