### ISSUE TITLE
Regression: `topic/johanna/table-changes` makes Zeek abort during startup

### ISSUE THREAD

**Issue by MaxKellermann** [zeek/zeek#787]
```
internal error: internal type TableChange missing

Thread 1 "zeek" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff51eb535 in __GI_abort () at abort.c:79
#2  0x000055555611947d in Reporter::InternalError (this=0x5555575ca9d0, fmt=0x5555562aeddb "internal type %s missing") at ../src/Reporter.cc:187
#3  0x0000555556194653 in internal_type (name=0x5555562a52aa "TableChange") at ../src/Var.cc:629
#4  0x000055555612416b in init_net_var () at src/types.bif.netvar_init:65
#5  0x0000555556034674 in main (argc=4, argv=0x7fffffffe768) at ../src/main.cc:652
```

This is my bisect (lots of commits failed to build):
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
5b5d36cd837a12a35813aa12c0e6b76f91256891
68167d14aa233591d92683ca3915d791119cbd29
96329e2172753c8d001430ba24a73cf1d3650983
b343cf9bb73555bb2ec119d428ad86ec762348c8
382c4ddc2f64f420c132f0a2350bf98ccc2171eb
bf31587c2c7adbcc783b285c2d12f971d8ed4e4e
98ad95d00bf339b84564809f6d42d2bbc80d3da7
We cannot bisect more!
```

**Comment by MaxKellermann** [comment]
After doing a complete rebuild, I cannot reproduce this anymore. So this might be a missing dependency in the cmake files, resulting in broken incremental builds... but not a true regression from merging Johanna's branch.
